export const accountStoreReviewCopy = {
  en: {
    browse: "Review the store",
    heading: "Store reviews",
    intro:
      "Share feedback about your store experience. All ratings are welcome.",
    privacy:
      "Your review may be shown publicly after moderation. Your email and order details are not displayed.",
    noInvitations: "You have no active store-review invitations.",
    loading: "Checking your invitations…",
    unavailable: "Invitations are temporarily unavailable. Try again.",
    loadMore: "Show more invitations",
    choose: "Review this order",
    order: "Order",
    expires: "Invitation expires",
    noReward: "No reward was promised for this invitation.",
    media: "Photos and videos are not available for store reviews.",
    rating: "Rating",
    ratingChoose: "Choose a rating",
    displayName: "Display name",
    title: "Title (optional)",
    body: "Your review",
    consent: "I agree to publish this review after moderation",
    submit: "Submit store review",
    retry: "Retry the same submission",
    invalid: "Check the rating, name, review and publication consent.",
    uncertain:
      "We could not confirm the result. Retry the same submission without changing it.",
    received: "Your store review was received.",
    continue: "Review another invitation",
  },
  ja: {
    browse: "ストアを評価する",
    heading: "ストアレビュー",
    intro: "ストアでの体験をお聞かせください。どの評価も歓迎します。",
    privacy:
      "レビューは確認後に公開される場合があります。メールアドレスと注文情報は表示されません。",
    noInvitations: "現在利用できるストアレビューの案内はありません。",
    loading: "案内を確認しています…",
    unavailable: "案内を一時的に確認できません。再度お試しください。",
    loadMore: "ほかの案内を表示",
    choose: "この注文を評価する",
    order: "注文",
    expires: "案内の有効期限",
    noReward: "この案内には特典の約束はありません。",
    media: "ストアレビューでは写真と動画を利用できません。",
    rating: "評価",
    ratingChoose: "評価を選択",
    displayName: "表示名",
    title: "タイトル（任意）",
    body: "レビュー",
    consent: "確認後のレビュー公開に同意します",
    submit: "ストアレビューを送信",
    retry: "同じ内容で再試行",
    invalid: "評価、表示名、レビュー、公開への同意を確認してください。",
    uncertain:
      "結果を確認できませんでした。内容を変更せずに同じ送信を再試行してください。",
    received: "ストアレビューを受け付けました。",
    continue: "別の案内を評価する",
  },
  vi: {
    browse: "Đánh giá cửa hàng",
    heading: "Đánh giá cửa hàng",
    intro:
      "Chia sẻ trải nghiệm của bạn với cửa hàng. Mọi mức đánh giá đều được chào đón.",
    privacy:
      "Đánh giá có thể được hiển thị công khai sau khi kiểm duyệt. Email và thông tin đơn hàng của bạn không được hiển thị.",
    noInvitations: "Bạn không có lời mời đánh giá cửa hàng nào còn hiệu lực.",
    loading: "Đang kiểm tra lời mời…",
    unavailable: "Tạm thời không thể xem lời mời. Vui lòng thử lại.",
    loadMore: "Xem thêm lời mời",
    choose: "Đánh giá đơn hàng này",
    order: "Đơn hàng",
    expires: "Lời mời hết hạn",
    noReward: "Lời mời này không hứa hẹn phần thưởng.",
    media: "Chưa hỗ trợ ảnh hoặc video cho đánh giá cửa hàng.",
    rating: "Xếp hạng",
    ratingChoose: "Chọn mức đánh giá",
    displayName: "Tên hiển thị",
    title: "Tiêu đề (không bắt buộc)",
    body: "Đánh giá của bạn",
    consent: "Tôi đồng ý công khai đánh giá sau khi kiểm duyệt",
    submit: "Gửi đánh giá cửa hàng",
    retry: "Thử gửi lại cùng nội dung",
    invalid: "Hãy kiểm tra xếp hạng, tên, nội dung và sự đồng ý công khai.",
    uncertain:
      "Chưa thể xác nhận kết quả. Hãy thử lại với đúng nội dung đã gửi.",
    received: "Đã nhận đánh giá cửa hàng của bạn.",
    continue: "Đánh giá lời mời khác",
  },
} as const;
