-- AlterTable
ALTER TABLE `WeleticLoyaltyOutboxJob` MODIFY `jobType` ENUM('HOLDING_PERIOD_RELEASE', 'INACTIVITY_EXPIRY', 'TIER_REVIEW', 'METAFIELD_SYNC', 'REDEMPTION_RECOVERY', 'BIRTHDAY_REWARD', 'REFERRAL_REWARD_PROVISION', 'VOUCHER_PRIVACY_CLEANUP', 'REVIEW_REQUEST_EMAIL', 'REVIEW_SUMMARY_SYNC', 'REVIEW_MEDIA_CLEANUP', 'FLOW_TRIGGER', 'SHOPPER_REWARD_PROVISION') NOT NULL;
