name = "Weletic Loyalty Account Blocks"
type = "ui_extension"
api_version = "2026-07"
uid = "5d7d6f93-bceb-4a0f-9bf8-41caac4083fd"

[[targeting]]
module = "./src/CustomerAccountLoyaltyBlocks.tsx"
target = "customer-account.profile.block.render"

[capabilities]
api_access = true
network_access = true
