const en = {
  expiredStatus: "Expired",
  unassigned: "Unassigned",
  title: "Loyalty analytics",
  language: "Language",
  start: "Start date (UTC)",
  end: "End date (UTC)",
  refresh: "Apply dates",
  loading: "Loading analytics…",
  error: "Analytics unavailable. Check your access and try again.",
  invalid: "Choose a valid date range.",
  unavailable: "Unavailable",
  empty: "No matching activity",
  csv: "Export CSV",
  json: "Export JSON",
  exportNote: "Financial exports are available to the store owner only.",
  semantics:
    "Balances and VIP distribution are current snapshots. Point activity uses the selected date range. Reward and referral statuses describe records created in that range, not a sequence of completed funnel steps. Empty dates include all history. Monetary values are exact minor units of the displayed currency (for example, cents for USD; yen for JPY).",
  financial:
    "Some financial metrics are unavailable. A valid valuation and reconciled order currencies are required. Unavailable values are not zero.",
  liability: "Current balances and liability",
  activity: "Point activity",
  referralEconomics: "Referral economics",
  referrals: "Referral status cohorts",
  rewards: "Reward utilization",
  tiers: "VIP distribution",
  currency: "Accounting currency",
  generated: "Generated at",
  status: "Status",
  artifact: "Artifact",
  count: "Count",
  pointsSpent: "Points spent",
  name: "Tier",
  members: "Members",
  pointsBalance: "Positive points balance",
  rollingSpendMinorUnits: "Rolling spend (minor units)",
  circulatingPoints: "Circulating points",
  pendingPoints: "Pending points",
  debtPoints: "Negative-balance debt points",
  currentMinorUnits: "Current liability (minor units)",
  pendingMinorUnits: "Pending liability (minor units)",
  potentialMinorUnits: "Potential liability (minor units)",
  totalMembers: "Total members",
  activeMembers: "Active members (90 days)",
  earned: "Earned points (includes backfill)",
  redeemed: "Redeemed points",
  refundReversed: "Refund-reversed points",
  expired: "Expired points",
  backfilled: "Backfilled points",
  backfillCorrected: "Backfill corrections",
  manualCredits: "Manual credits",
  manualDebits: "Manual debits",
  total: "Total referrals",
  successful: "Successful referrals",
  revenueMinorUnits: "Revenue (minor units)",
  costMinorUnits: "Reward cost (minor units)",
  pending: "Pending",
  qualified: "Qualified",
  rewarded: "Rewarded",
  cancelled: "Cancelled",
  fraud_blocked: "Fraud blocked",
  active: "Active",
  provisioning: "Provisioning",
  issued: "Issued",
  used: "Used",
  failed: "Failed",
  discount_code: "Discount code",
  gift_card: "Gift card",
  store_credit: "Store credit",
};
type Copy = Record<keyof typeof en, string>;
const ja: Copy = {
  expiredStatus: "期限切れ",
  unassigned: "未設定",
  title: "ロイヤルティ分析",
  language: "言語",
  start: "開始日（UTC）",
  end: "終了日（UTC）",
  refresh: "期間を適用",
  loading: "分析を読み込み中…",
  error: "分析を取得できません。アクセス権を確認して再試行してください。",
  invalid: "有効な期間を選択してください。",
  unavailable: "利用不可",
  empty: "該当する履歴はありません",
  csv: "CSVを出力",
  json: "JSONを出力",
  exportNote: "財務データの出力はストアオーナーのみ利用できます。",
  semantics:
    "残高とVIP分布は現在の状態です。ポイント履歴には選択した期間を適用します。特典と紹介のステータスは、その期間に作成された記録の現在の状態であり、順番に完了したファネルの段階ではありません。日付が空欄の場合は全期間です。金額は表示通貨の最小単位の正確な値です（USDはセント、JPYは円）。",
  financial:
    "一部の財務指標は利用できません。有効なポイント評価と注文通貨の照合が必要です。利用不可はゼロを意味しません。",
  liability: "現在の残高と負債",
  activity: "ポイント履歴",
  referralEconomics: "紹介の収益と費用",
  referrals: "紹介のステータス別集計",
  rewards: "特典の利用状況",
  tiers: "VIP分布",
  currency: "会計通貨",
  generated: "生成日時",
  status: "ステータス",
  artifact: "特典形式",
  count: "件数",
  pointsSpent: "使用ポイント",
  name: "ランク",
  members: "会員数",
  pointsBalance: "正のポイント残高",
  rollingSpendMinorUnits: "期間内購入額（最小通貨単位）",
  circulatingPoints: "流通ポイント",
  pendingPoints: "保留ポイント",
  debtPoints: "マイナス残高の債務ポイント",
  currentMinorUnits: "現在の負債（最小通貨単位）",
  pendingMinorUnits: "保留分の負債（最小通貨単位）",
  potentialMinorUnits: "潜在負債（最小通貨単位）",
  totalMembers: "総会員数",
  activeMembers: "アクティブ会員（90日）",
  earned: "獲得ポイント（過去分補填を含む）",
  redeemed: "利用ポイント",
  refundReversed: "返金に伴う取消ポイント",
  expired: "失効ポイント",
  backfilled: "過去分補填ポイント",
  backfillCorrected: "過去分補填の修正",
  manualCredits: "手動加算",
  manualDebits: "手動減算",
  total: "紹介総数",
  successful: "成功した紹介",
  revenueMinorUnits: "売上（最小通貨単位）",
  costMinorUnits: "特典費用（最小通貨単位）",
  pending: "保留",
  qualified: "条件達成",
  rewarded: "付与済み",
  cancelled: "取消済み",
  fraud_blocked: "不正防止による停止",
  active: "有効",
  provisioning: "発行処理中",
  issued: "発行済み",
  used: "使用済み",
  failed: "失敗",
  discount_code: "割引コード",
  gift_card: "ギフトカード",
  store_credit: "ストアクレジット",
};
const vi: Copy = {
  expiredStatus: "Đã hết hạn",
  unassigned: "Chưa phân hạng",
  title: "Phân tích khách hàng thân thiết",
  language: "Ngôn ngữ",
  start: "Ngày bắt đầu (UTC)",
  end: "Ngày kết thúc (UTC)",
  refresh: "Áp dụng ngày",
  loading: "Đang tải phân tích…",
  error: "Không thể tải phân tích. Hãy kiểm tra quyền truy cập và thử lại.",
  invalid: "Chọn khoảng ngày hợp lệ.",
  unavailable: "Không khả dụng",
  empty: "Không có hoạt động phù hợp",
  csv: "Xuất CSV",
  json: "Xuất JSON",
  exportNote: "Chỉ chủ cửa hàng có quyền xuất dữ liệu tài chính.",
  semantics:
    "Số dư và phân bố VIP phản ánh trạng thái hiện tại. Hoạt động điểm được lọc theo khoảng ngày đã chọn. Trạng thái phần thưởng và giới thiệu phản ánh các bản ghi được tạo trong khoảng đó, không phải các bước liên tiếp đã hoàn thành. Để trống ngày để xem toàn bộ lịch sử. Giá trị tiền là số chính xác theo đơn vị nhỏ nhất của đồng tiền hiển thị (ví dụ: cent với USD, yên với JPY).",
  financial:
    "Một số chỉ số tài chính chưa khả dụng. Cần định giá điểm hợp lệ và đối soát tiền tệ đơn hàng. Không khả dụng không có nghĩa là bằng không.",
  liability: "Số dư và nghĩa vụ hiện tại",
  activity: "Hoạt động điểm",
  referralEconomics: "Doanh thu và chi phí giới thiệu",
  referrals: "Nhóm trạng thái giới thiệu",
  rewards: "Sử dụng phần thưởng",
  tiers: "Phân bố VIP",
  currency: "Tiền tệ kế toán",
  generated: "Thời điểm tổng hợp",
  status: "Trạng thái",
  artifact: "Loại phần thưởng",
  count: "Số lượng",
  pointsSpent: "Điểm đã dùng",
  name: "Hạng",
  members: "Thành viên",
  pointsBalance: "Số dư điểm dương",
  rollingSpendMinorUnits: "Chi tiêu trong kỳ (đơn vị nhỏ nhất)",
  circulatingPoints: "Điểm đang lưu hành",
  pendingPoints: "Điểm đang chờ",
  debtPoints: "Nợ điểm do số dư âm",
  currentMinorUnits: "Nghĩa vụ hiện tại (đơn vị nhỏ nhất)",
  pendingMinorUnits: "Nghĩa vụ đang chờ (đơn vị nhỏ nhất)",
  potentialMinorUnits: "Nghĩa vụ tiềm năng (đơn vị nhỏ nhất)",
  totalMembers: "Tổng thành viên",
  activeMembers: "Thành viên hoạt động (90 ngày)",
  earned: "Điểm đã tích (gồm bổ sung lịch sử)",
  redeemed: "Điểm đã đổi",
  refundReversed: "Điểm thu hồi do hoàn tiền",
  expired: "Điểm hết hạn",
  backfilled: "Điểm bổ sung lịch sử",
  backfillCorrected: "Điều chỉnh bổ sung lịch sử",
  manualCredits: "Cộng điểm thủ công",
  manualDebits: "Trừ điểm thủ công",
  total: "Tổng lượt giới thiệu",
  successful: "Giới thiệu thành công",
  revenueMinorUnits: "Doanh thu (đơn vị nhỏ nhất)",
  costMinorUnits: "Chi phí phần thưởng (đơn vị nhỏ nhất)",
  pending: "Đang chờ",
  qualified: "Đủ điều kiện",
  rewarded: "Đã thưởng",
  cancelled: "Đã hủy",
  fraud_blocked: "Bị chặn do gian lận",
  active: "Đang hoạt động",
  provisioning: "Đang cấp",
  issued: "Đã cấp",
  used: "Đã sử dụng",
  failed: "Thất bại",
  discount_code: "Mã giảm giá",
  gift_card: "Thẻ quà tặng",
  store_credit: "Tín dụng cửa hàng",
};
export const merchantAnalyticsCopy = { en, ja, vi };
