const en = {
  expiredStatus: "Expired",
  unassigned: "Unassigned",
  title: "Loyalty analytics",
  language: "Language",
  start: "Start date (UTC)",
  end: "End date (UTC)",
  refresh: "Apply dates",
  loading: "Loading analytics…",
  error: "Analytics unavailable. Check your access and try again.",
  invalid: "Choose a valid date range.",
  unavailable: "Unavailable",
  empty: "No matching activity",
  csv: "Export CSV",
  json: "Export JSON",
  exportNote: "Financial exports are available to the store owner only.",
  accountRowsTitle: "Current recorded members",
  accountRowsCsv: "Export current members CSV",
  accountRowsSemantics:
    "Owner-only export of up to 2,000 retained, non-redacted accounts enrolled within 366 UTC days. Select both dates first. Status, tier order and cached balances are current snapshots, not historical values or independent ledger reconciliation. Point values are exact integer strings; import numeric columns as text. Account keys are pseudonyms specific to this report and cannot be joined to other exports. Customer identity, contact details, referral codes and erased history are unavailable.",
  tierHistoryTitle: "Recorded VIP tier history",
  tierHistoryCsv: "Export tier events CSV",
  ledgerRowsTitle: "Recorded points transactions",
  ledgerRowsCsv: "Export points transactions CSV",
  ledgerRowsSemantics:
    "Owner-only export of up to 2,000 retained, non-redacted ledger entries within 366 UTC days. Select both dates first. Points, pending points and balances are exact integer strings in the file. Import numeric columns as text in spreadsheet apps to avoid rounding long values. Account IDs are pseudonyms; shopper, order, grant and raw reference fields are omitted. Missing or erased history is unavailable.",
  redemptionRowsTitle: "Recorded points redemptions",
  redemptionRowsCsv: "Export recorded redemptions CSV",
  redemptionRowsSemantics:
    "Owner-only export of up to 2,000 retained, non-redacted points redemptions created within 366 UTC days. Current status is a snapshot, not a status history; use time may fall outside the selected range. Account and redemption keys are pseudonyms. Codes, customers, orders and free-text fields are omitted. Point strings are exact; import the points column as text in spreadsheet apps. Missing or erased history and zero-point shopper coupons are unavailable.",
  tooMany: "More than 2,000 rows match. Choose a shorter date range.",
  tierHistorySemantics:
    "Owner-only export of up to 2,000 retained, non-redacted tier events within 366 UTC days. Select both dates first. Larger results require a shorter date range; no partial file is downloaded. Account IDs are pseudonyms; tier names are their current labels, not labels captured when the event occurred. Missing or erased history and past membership are unavailable.",
  semantics:
    "Balances and VIP distribution are current snapshots. Point activity uses the selected date range. Reward and referral statuses describe records created in that range, not a sequence of completed funnel steps. Empty dates include all history. Monetary values are exact minor units of the displayed currency (for example, cents for USD; yen for JPY).",
  financial:
    "Some financial metrics are unavailable. A valid valuation and reconciled order currencies are required. Unavailable values are not zero.",
  liability: "Current balances and liability",
  activity: "Point activity",
  activitySeries: "Daily point activity (UTC)",
  ledgerNetSeries: "Recorded ledger net over time (UTC)",
  firstRecordedEarnersSeries:
    "First recorded and returning earn accounts (UTC)",
  firstRecordedEarnersSemantics:
    "Counts distinct accounts with positive recorded order, referral, bonus or tier earnings in each UTC month. First means the account's earliest retained qualifying earn is inside the selected instants; later months are returning. An earlier earn in the same month but before the selected start makes the account returning. Imports and manual adjustments do not qualify. Missing pre-Weletic or erased history and multiple accounts cannot be reconstructed; these are not lifetime customer cohorts.",
  firstRecordedRedemptionDebitsSeries:
    "First recorded and repeat reward-debit accounts (UTC)",
  firstRecordedRedemptionDebitsSemantics:
    "Counts distinct currently retained accounts with a negative recorded reward-redemption debit in each UTC month. First means no earlier retained debit before the selected instant or month; a debit before the range, even in the same month, makes the account repeat. A debit can occur during provisioning and later be compensated, so this does not prove successful issuance or use. Erased or pre-Weletic history and multiple accounts cannot be reconstructed; these are not lifetime shopper cohorts.",
  debitAccounts: "Accounts with recorded debits",
  firstRecordedDebitAccounts: "First recorded debit accounts",
  returningDebitAccounts: "Repeat debit accounts",
  retainedEnrollmentSeries: "Retained account enrollments over time (UTC)",
  retainedEnrollmentOpening: "Retained accounts before selected range",
  retainedEnrollmentSemantics:
    "Counts Loyalty accounts still retained now by their recorded enrollment time. Each cumulative count adds enrollments within the selected instants to the retained accounts enrolled before the start; boundary months may be partial. Erased accounts and missing pre-Weletic history cannot be reconstructed. This is not past active membership or a Shopify customer total.",
  openingRetainedAccounts: "Retained accounts before range",
  newRetainedAccounts: "New recorded enrollments",
  cumulativeRetainedAccounts: "Cumulative retained accounts",
  earningSources: "Top recorded earning sources",
  earningSourcesSemantics:
    "Ranks retained positive earning-ledger entries by gross points in the selected instants. Event count is ledger entries, not unique customers or orders. Later refunds stay separate, so this is not net points or a lifetime store measure. Historical imports and manual adjustments are excluded; missing or erased history is unavailable.",
  entryType: "Earning source",
  redemptionSources: "Top recorded redemption debits",
  redemptionSourcesTotal: "Recorded redemption debit totals",
  redemptionSourcesSemantics:
    "Ranks retained reward-debit ledger entries by gross points in the selected instants. Names and types are captured at debit; the linked redemption confirms only the reward ID and points. Missing or inconsistent provenance is Unknown. Other combines groups outside the top ten. These are debit events, not remote discount uses or net cost: cancellations and refunds remain separate. Zero-point direct awards and missing or erased history are unavailable here.",
  group: "Provenance group",
  recordedReward: "Recorded reward",
  otherRewards: "Other recorded rewards",
  unknownReward: "Unknown provenance",
  rewardDefinitionId: "Reward definition ID",
  capturedName: "Name captured at debit",
  rewardType: "Reward type",
  redemptionEvents: "Recorded debit events",
  grossRedemptionPoints: "Gross points debited",
  amount_off: "Amount off",
  percentage_off: "Percentage off",
  free_shipping: "Free shipping",
  free_product: "Free product",
  eventCount: "Recorded earning events",
  pointsEarned: "Gross earned points",
  EARN_ORDER: "Order",
  EARN_REFERRAL: "Referral",
  EARN_BONUS: "Bonus",
  TIER_BONUS: "VIP tier bonus",
  activeAccounts: "Active earning accounts",
  firstRecordedAccounts: "First recorded earn accounts",
  returningAccounts: "Returning earn accounts",
  recordedTierChangesSeries: "Recorded VIP tier events by reason (UTC)",
  recordedTierChangesSemantics:
    "Counts retained tier-history events by their stored reason in each UTC month. Boundary months may be partial. Reasons do not prove promotion or demotion direction, historical tier membership, or missing and erased history. Imported and manual events remain in their recorded reason groups.",
  totalChanges: "Recorded tier events",
  thresholdReached: "Threshold reached",
  bonusPromotion: "Bonus promotion reason",
  annualDowngrade: "Annual downgrade reason",
  gracePeriodExpired: "Grace period expired",
  programActivation: "Program activation",
  manualOverride: "Manual override",
  otherReasons: "Other recorded reasons",
  ledgerNetOpening: "Recorded net before the selected range",
  ledgerNetSemantics:
    "This is the signed sum of retained point-ledger entries before and within the selected instants. The first and last UTC days may be partial. It is not historical outstanding liability: missing pre-Weletic history and account-level debt are not reconstructed.",
  openingNetPoints: "Opening recorded net points",
  netChangePoints: "Daily net change",
  cumulativeNetPoints: "Cumulative recorded net",
  redemptionRateSeries: "Monthly redemption-to-earn rate (UTC)",
  redemptionRateSemantics:
    "Within the selected interval in each UTC month, recorded reward-spend points are divided by recorded earned points; boundary months may be partial. Earned points exclude backfills; refund reversals, expiry and manual adjustments stay separate. Canceled rewards remain in gross spend while restoration credits stay in manual adjustments. Spending earlier earnings can make this rate exceed 100%. A month with no qualifying earned points has no rate. This is not discount usage or a whole-store measure.",
  month: "UTC month",
  earnedPoints: "Earned points, excluding backfill",
  redeemedPoints: "Reward-spend points",
  redemptionRateBasisPoints: "Redemption-to-earn rate",
  orderEarningSeries: "Recorded order earning rate (UTC)",
  orderEarningSemantics:
    "Only orders recorded by Weletic are counted, including pending and voided records. Dates use the order timestamp. A positive recorded purchase-points grant counts once, including backfills and later-refunded grants; this is not a measure of points still held. Missing Shopify orders are outside this report, so it does not establish a whole-store rate.",
  recordedOrders: "Recorded orders",
  earningOrders: "Orders with positive points grant",
  rateBasisPoints: "Earning rate",
  range_required: "Select both dates to view up to 366 UTC days.",
  range_too_wide: "Choose a range of at most 366 UTC days.",
  date: "UTC date",
  referralEconomics: "Referral economics",
  referrals: "Referral status cohorts",
  rewards: "Reward utilization",
  tiers: "VIP distribution",
  currency: "Accounting currency",
  generated: "Generated at",
  status: "Status",
  artifact: "Artifact",
  count: "Count",
  pointsSpent: "Points spent",
  name: "Tier",
  members: "Members",
  pointsBalance: "Positive points balance",
  rollingSpendMinorUnits: "Rolling spend (minor units)",
  circulatingPoints: "Circulating points",
  pendingPoints: "Pending points",
  debtPoints: "Negative-balance debt points",
  currentMinorUnits: "Current liability (minor units)",
  pendingMinorUnits: "Pending liability (minor units)",
  potentialMinorUnits: "Potential liability (minor units)",
  totalMembers: "Total members",
  activeMembers: "Active members (90 days)",
  earned: "Earned points (includes backfill)",
  redeemed: "Redeemed points",
  refundReversed: "Refund-reversed points",
  expired: "Expired points",
  backfilled: "Backfilled points",
  backfillCorrected: "Backfill corrections",
  manualCredits: "Manual credits",
  manualDebits: "Manual debits",
  total: "Total referrals",
  successful: "Successful referrals",
  revenueMinorUnits: "Revenue (minor units)",
  costMinorUnits: "Reward cost (minor units)",
  pending: "Pending",
  qualified: "Qualified",
  rewarded: "Rewarded",
  cancelled: "Cancelled",
  fraud_blocked: "Fraud blocked",
  active: "Active",
  provisioning: "Provisioning",
  issued: "Issued",
  used: "Used",
  failed: "Failed",
  discount_code: "Discount code",
  gift_card: "Gift card",
  store_credit: "Store credit",
};
type Copy = Record<keyof typeof en, string>;
const ja: Copy = {
  expiredStatus: "期限切れ",
  unassigned: "未設定",
  title: "ロイヤルティ分析",
  language: "言語",
  start: "開始日（UTC）",
  end: "終了日（UTC）",
  refresh: "期間を適用",
  loading: "分析を読み込み中…",
  error: "分析を取得できません。アクセス権を確認して再試行してください。",
  invalid: "有効な期間を選択してください。",
  unavailable: "利用不可",
  empty: "該当する履歴はありません",
  csv: "CSVを出力",
  json: "JSONを出力",
  exportNote: "財務データの出力はストアオーナーのみ利用できます。",
  accountRowsTitle: "記録済み会員の現在の状態",
  accountRowsCsv: "現在の会員CSVを出力",
  accountRowsSemantics:
    "オーナー限定。UTCで最大366日間に登録された、保持済みで削除されていないアカウントを最大2,000件出力します。開始日と終了日を選択してください。状態、ランク順、保存済み残高は現在の値であり、過去の値や台帳との独立した照合結果ではありません。ポイントは正確な整数文字列です。表計算アプリでは数値列をテキストとして読み込んでください。仮名化されたアカウントキーはこのレポート専用で、他の出力とは結合できません。顧客の識別情報、連絡先、紹介コード、削除済み履歴は含まれません。",
  tierHistoryTitle: "記録されたVIPランク履歴",
  tierHistoryCsv: "ランク履歴CSVを出力",
  ledgerRowsTitle: "記録されたポイント取引",
  ledgerRowsCsv: "ポイント取引CSVを出力",
  ledgerRowsSemantics:
    "オーナー限定。UTCで最大366日間の保持済み・非削除の台帳記録を最大2,000件出力します。開始日と終了日を選択してください。ファイル内のポイント、保留ポイント、残高は正確な整数文字列です。表計算アプリで桁数の多い値が丸められないよう、数値列をテキストとして読み込んでください。アカウントIDは仮名化され、顧客・注文・付与・参照の生データは含まれません。欠損または削除済みの履歴は利用できません。",
  redemptionRowsTitle: "記録されたポイント交換",
  redemptionRowsCsv: "ポイント交換CSVを出力",
  redemptionRowsSemantics:
    "オーナー限定。UTCで最大366日間に作成された保持済み・非削除のポイント交換を最大2,000件出力します。現在の状態は履歴ではなくスナップショットです。利用日は選択期間外の場合があります。アカウントと交換のキーは仮名化され、コード・顧客・注文・自由記述は含まれません。ポイント値は正確な整数文字列です。表計算アプリでは数値列をテキストとして読み込んでください。欠損・削除済みの履歴とポイントを使わない顧客クーポンは対象外です。",
  tooMany: "該当する行が2,000件を超えています。期間を短くしてください。",
  tierHistorySemantics:
    "ストアオーナーのみ、最大366日間の保持中かつ非削除のランク履歴を2,000件まで出力できます。両方の日付を選択してください。超過した場合は期間を短くしてください。部分的なファイルは出力しません。アカウントIDは仮名化され、ランク名は変更当時ではなく現在の名称です。欠落・削除済みの履歴や過去の所属は利用できません。",
  semantics:
    "残高とVIP分布は現在の状態です。ポイント履歴には選択した期間を適用します。特典と紹介のステータスは、その期間に作成された記録の現在の状態であり、順番に完了したファネルの段階ではありません。日付が空欄の場合は全期間です。金額は表示通貨の最小単位の正確な値です（USDはセント、JPYは円）。",
  financial:
    "一部の財務指標は利用できません。有効なポイント評価と注文通貨の照合が必要です。利用不可はゼロを意味しません。",
  liability: "現在の残高と負債",
  activity: "ポイント履歴",
  activitySeries: "日別ポイント履歴（UTC）",
  ledgerNetSeries: "記録済み台帳の累積純増減（UTC）",
  firstRecordedEarnersSeries: "初回記録と再獲得のアカウント（UTC）",
  firstRecordedEarnersSemantics:
    "各UTC月に注文、紹介、ボーナス、ランクによる正の獲得が記録されたアカウントを重複なく数えます。初回は保存された対象履歴の最初の獲得が選択期間内にある場合です。同じ月でも期間開始前に獲得があれば再獲得に分類します。過去分補填と手動調整は対象外です。Weletic導入前や削除済みの履歴、複数アカウントの統合は復元できず、生涯の顧客コホートではありません。",
  firstRecordedRedemptionDebitsSeries:
    "初回記録と再記録の報酬ポイント引落アカウント（UTC）",
  firstRecordedRedemptionDebitsSemantics:
    "各UTC月に報酬交換の負のポイント引落が記録された、現在保持中のアカウントを重複なく数えます。初回は選択時点または月より前に保存された同種の引落がない場合です。同じ月でも期間開始前に引落があれば再記録に分類します。引落は発行処理中に記録され、後で補償されることもあるため、発行や利用の成功を示しません。削除済み・Weletic導入前の履歴や複数アカウントの統合は復元できず、生涯の顧客コホートではありません。",
  debitAccounts: "引落が記録されたアカウント",
  firstRecordedDebitAccounts: "初回引落記録のアカウント",
  returningDebitAccounts: "再引落記録のアカウント",
  retainedEnrollmentSeries: "保持中アカウントの登録推移（UTC）",
  retainedEnrollmentOpening: "選択期間前の保持中アカウント",
  retainedEnrollmentSemantics:
    "現在保持されているロイヤルティアカウントを記録された登録日時で数えます。開始前の件数に、選択期間内の各UTC月の新規登録を加えた累計です。境界月は一部のみです。削除済みアカウントやWeletic導入前の履歴は復元できず、過去時点の有効会員数やShopify顧客総数ではありません。",
  openingRetainedAccounts: "期間開始前の保持中アカウント",
  newRetainedAccounts: "記録された新規登録",
  cumulativeRetainedAccounts: "保持中アカウントの累計",
  earningSources: "記録済みポイント獲得源の順位",
  earningSourcesSemantics:
    "選択した期間の正の獲得台帳を、総獲得ポイントで並べます。件数は台帳の記録数で、顧客数や注文数ではありません。後の返金は別に記録するため、純増減やストアの生涯値ではありません。過去分補填と手動調整は除外し、欠損または削除済みの履歴は利用できません。",
  entryType: "獲得源",
  redemptionSources: "記録された特典交換のポイント引落上位",
  redemptionSourcesTotal: "記録された交換引落の合計",
  redemptionSourcesSemantics:
    "選択範囲の特典交換によるポイント引落台帳記録を総ポイント順に表示します。名称と種類は引落時の記録です。関連する交換記録で確認できるのは特典IDとポイント数のみです。情報が欠落または不一致の場合は不明、上位10件以外はその他に含めます。これは実際の割引利用や純費用ではありません。取消と返金は別記録です。ゼロポイントの直接付与と欠落・削除済み履歴は含みません。",
  group: "情報グループ",
  recordedReward: "記録された特典",
  otherRewards: "その他の記録された特典",
  unknownReward: "情報不明",
  rewardDefinitionId: "特典定義ID",
  capturedName: "引落時の名称",
  rewardType: "特典の種類",
  redemptionEvents: "記録された引落件数",
  grossRedemptionPoints: "引落総ポイント",
  amount_off: "定額割引",
  percentage_off: "割合割引",
  free_shipping: "送料無料",
  free_product: "無料商品",
  eventCount: "記録済み獲得件数",
  pointsEarned: "獲得ポイント総数",
  EARN_ORDER: "注文",
  EARN_REFERRAL: "紹介",
  EARN_BONUS: "ボーナス",
  TIER_BONUS: "VIPランクボーナス",
  activeAccounts: "獲得したアカウント",
  firstRecordedAccounts: "記録上の初回獲得アカウント",
  returningAccounts: "再獲得アカウント",
  recordedTierChangesSeries: "記録されたVIPランク変更理由（UTC）",
  recordedTierChangesSemantics:
    "保存されたランク履歴のイベントをUTC月ごとに記録済みの理由別で数えます。期間の初月と最終月は一部のみの場合があります。理由だけでは昇格・降格の方向、過去のランク所属、欠落・削除済みの履歴は証明できません。インポートと手動操作も記録された理由で分類します。",
  totalChanges: "記録されたランクイベント",
  thresholdReached: "しきい値到達",
  bonusPromotion: "ボーナス昇格理由",
  annualDowngrade: "年次降格理由",
  gracePeriodExpired: "猶予期間終了",
  programActivation: "プログラム有効化",
  manualOverride: "手動変更",
  otherReasons: "その他の記録済み理由",
  ledgerNetOpening: "選択期間前の記録済み純増減",
  ledgerNetSemantics:
    "保存されたポイント台帳の増減を、選択した期間の前と期間内で合計します。期間の最初と最後のUTC日は一部のみを含む場合があります。Weletic導入前の履歴や会員ごとのマイナス残高は復元していないため、過去の未履行債務を示すものではありません。",
  openingNetPoints: "開始前の記録済み純増減ポイント",
  netChangePoints: "日別の純増減",
  cumulativeNetPoints: "記録済み累積純増減",
  redemptionRateSeries: "月別ポイント利用・獲得比率（UTC）",
  redemptionRateSemantics:
    "選択した期間内の各UTC月に記録された特典交換の使用ポイントを、同じ期間の獲得ポイントで割った比率です。期間の端にある月は一部の日付のみを含む場合があります。獲得ポイントに過去分補填は含めず、返金による取戻し、失効、手動調整は別に扱います。取り消された特典の元の使用ポイントは残り、返還分は手動調整に分けて記録されます。以前に獲得したポイントを使うと100%を超える場合があります。対象の獲得がない月は比率を表示しません。割引の利用率やストア全体の指標ではありません。",
  month: "UTC月",
  earnedPoints: "獲得ポイント（過去分補填を除く）",
  redeemedPoints: "特典交換の使用ポイント",
  redemptionRateBasisPoints: "ポイント利用・獲得比率",
  orderEarningSeries: "記録済み注文のポイント獲得率（UTC）",
  orderEarningSemantics:
    "Weleticに記録された注文のみを集計し、保留中と無効の注文も含めます。日付は注文日時です。正の購入ポイント付与が記録された注文は、過去分補填や後で返金された付与も1件として数えます。現在保有するポイント数の指標ではありません。記録のない注文は含まれないため、ストア全体の獲得率は示しません。",
  recordedOrders: "記録済み注文",
  earningOrders: "正のポイント付与がある注文",
  rateBasisPoints: "獲得率",
  range_required: "両方の日付を選択すると、最大366日間を表示できます。",
  range_too_wide: "366日以内の期間を選択してください。",
  date: "UTCの日付",
  referralEconomics: "紹介の収益と費用",
  referrals: "紹介のステータス別集計",
  rewards: "特典の利用状況",
  tiers: "VIP分布",
  currency: "会計通貨",
  generated: "生成日時",
  status: "ステータス",
  artifact: "特典形式",
  count: "件数",
  pointsSpent: "使用ポイント",
  name: "ランク",
  members: "会員数",
  pointsBalance: "正のポイント残高",
  rollingSpendMinorUnits: "期間内購入額（最小通貨単位）",
  circulatingPoints: "流通ポイント",
  pendingPoints: "保留ポイント",
  debtPoints: "マイナス残高の債務ポイント",
  currentMinorUnits: "現在の負債（最小通貨単位）",
  pendingMinorUnits: "保留分の負債（最小通貨単位）",
  potentialMinorUnits: "潜在負債（最小通貨単位）",
  totalMembers: "総会員数",
  activeMembers: "アクティブ会員（90日）",
  earned: "獲得ポイント（過去分補填を含む）",
  redeemed: "利用ポイント",
  refundReversed: "返金に伴う取消ポイント",
  expired: "失効ポイント",
  backfilled: "過去分補填ポイント",
  backfillCorrected: "過去分補填の修正",
  manualCredits: "手動加算",
  manualDebits: "手動減算",
  total: "紹介総数",
  successful: "成功した紹介",
  revenueMinorUnits: "売上（最小通貨単位）",
  costMinorUnits: "特典費用（最小通貨単位）",
  pending: "保留",
  qualified: "条件達成",
  rewarded: "付与済み",
  cancelled: "取消済み",
  fraud_blocked: "不正防止による停止",
  active: "有効",
  provisioning: "発行処理中",
  issued: "発行済み",
  used: "使用済み",
  failed: "失敗",
  discount_code: "割引コード",
  gift_card: "ギフトカード",
  store_credit: "ストアクレジット",
};
const vi: Copy = {
  expiredStatus: "Đã hết hạn",
  unassigned: "Chưa phân hạng",
  title: "Phân tích khách hàng thân thiết",
  language: "Ngôn ngữ",
  start: "Ngày bắt đầu (UTC)",
  end: "Ngày kết thúc (UTC)",
  refresh: "Áp dụng ngày",
  loading: "Đang tải phân tích…",
  error: "Không thể tải phân tích. Hãy kiểm tra quyền truy cập và thử lại.",
  invalid: "Chọn khoảng ngày hợp lệ.",
  unavailable: "Không khả dụng",
  empty: "Không có hoạt động phù hợp",
  csv: "Xuất CSV",
  json: "Xuất JSON",
  exportNote: "Chỉ chủ cửa hàng có quyền xuất dữ liệu tài chính.",
  accountRowsTitle: "Thành viên đã ghi nhận hiện tại",
  accountRowsCsv: "Xuất CSV thành viên hiện tại",
  accountRowsSemantics:
    "Chỉ chủ cửa hàng được xuất tối đa 2.000 tài khoản còn lưu, chưa bị xóa dữ liệu và đăng ký trong tối đa 366 ngày UTC. Hãy chọn cả hai ngày. Trạng thái, thứ tự hạng và số dư đã lưu là ảnh chụp hiện tại, không phải giá trị lịch sử hay kết quả đối soát độc lập với sổ cái. Điểm là chuỗi số nguyên chính xác; hãy nhập cột số dưới dạng văn bản trong bảng tính. Khóa tài khoản được thay bằng bút danh riêng cho báo cáo này và không thể ghép với các bản xuất khác. Không gồm danh tính, liên hệ, mã giới thiệu hay lịch sử đã xóa.",
  tierHistoryTitle: "Lịch sử hạng VIP đã ghi nhận",
  tierHistoryCsv: "Xuất CSV sự kiện hạng",
  ledgerRowsTitle: "Giao dịch điểm đã ghi nhận",
  ledgerRowsCsv: "Xuất CSV giao dịch điểm",
  ledgerRowsSemantics:
    "Chỉ chủ cửa hàng được xuất tối đa 2.000 bút toán còn lưu và chưa bị xóa trong tối đa 366 ngày UTC. Chọn cả ngày bắt đầu và kết thúc. Điểm, điểm chờ và số dư là chuỗi số nguyên chính xác trong tệp. Hãy nhập các cột số dưới dạng văn bản trong ứng dụng bảng tính để tránh làm tròn số dài. ID tài khoản được thay bằng mã ẩn danh; không gồm dữ liệu gốc về khách hàng, đơn hàng, lần cấp hay tham chiếu. Lịch sử thiếu hoặc đã xóa không khả dụng.",
  redemptionRowsTitle: "Lượt đổi điểm đã ghi nhận",
  redemptionRowsCsv: "Xuất CSV lượt đổi điểm",
  redemptionRowsSemantics:
    "Chỉ chủ cửa hàng được xuất tối đa 2.000 lượt đổi điểm còn lưu, chưa bị xóa và được tạo trong tối đa 366 ngày UTC. Trạng thái hiện tại là ảnh chụp, không phải lịch sử trạng thái; ngày sử dụng có thể ngoài khoảng đã chọn. Mã tài khoản và lượt đổi được ẩn danh; không gồm mã ưu đãi, khách hàng, đơn hàng hay văn bản tự do. Giá trị điểm là chuỗi số nguyên chính xác; hãy nhập cột điểm dưới dạng văn bản trong bảng tính. Lịch sử thiếu hoặc đã xóa và phiếu không dùng điểm không khả dụng.",
  tooMany: "Có hơn 2.000 dòng phù hợp. Hãy chọn khoảng ngày ngắn hơn.",
  tierHistorySemantics:
    "Chỉ chủ cửa hàng được xuất tối đa 2.000 sự kiện hạng còn lưu, chưa bị xóa dữ liệu trong khoảng tối đa 366 ngày UTC. Hãy chọn cả hai ngày. Nếu vượt giới hạn, hãy thu hẹp khoảng ngày; hệ thống không tải tệp thiếu dữ liệu. ID tài khoản được thay bằng bút danh; tên hạng là tên hiện tại, không phải tên lúc xảy ra sự kiện. Lịch sử thiếu hoặc đã xóa và tư cách hạng trong quá khứ không khả dụng.",
  semantics:
    "Số dư và phân bố VIP phản ánh trạng thái hiện tại. Hoạt động điểm được lọc theo khoảng ngày đã chọn. Trạng thái phần thưởng và giới thiệu phản ánh các bản ghi được tạo trong khoảng đó, không phải các bước liên tiếp đã hoàn thành. Để trống ngày để xem toàn bộ lịch sử. Giá trị tiền là số chính xác theo đơn vị nhỏ nhất của đồng tiền hiển thị (ví dụ: cent với USD, yên với JPY).",
  financial:
    "Một số chỉ số tài chính chưa khả dụng. Cần định giá điểm hợp lệ và đối soát tiền tệ đơn hàng. Không khả dụng không có nghĩa là bằng không.",
  liability: "Số dư và nghĩa vụ hiện tại",
  activity: "Hoạt động điểm",
  activitySeries: "Hoạt động điểm theo ngày (UTC)",
  ledgerNetSeries: "Biến động ròng tích lũy theo sổ điểm (UTC)",
  firstRecordedEarnersSeries: "Tài khoản tích điểm lần đầu và quay lại (UTC)",
  firstRecordedEarnersSemantics:
    "Đếm mỗi tài khoản một lần trong từng tháng UTC khi có điểm dương từ đơn hàng, giới thiệu, thưởng hoặc hạng. Lần đầu nghĩa là khoản tích điểm đủ điều kiện sớm nhất còn lưu nằm trong khoảng đã chọn; các tháng sau là quay lại. Nếu khoản đầu tiên nằm trước thời điểm bắt đầu dù cùng tháng, tài khoản được tính là quay lại. Không tính điểm nhập lịch sử hoặc điều chỉnh thủ công. Không thể khôi phục lịch sử trước Weletic, lịch sử đã xóa hay hợp nhất nhiều tài khoản; đây không phải nhóm khách hàng theo toàn bộ vòng đời.",
  firstRecordedRedemptionDebitsSeries:
    "Tài khoản ghi nhận lần đầu và lặp lại khoản trừ điểm đổi thưởng (UTC)",
  firstRecordedRedemptionDebitsSemantics:
    "Đếm mỗi tài khoản hiện còn lưu một lần trong từng tháng UTC khi có bút toán trừ điểm âm để đổi thưởng. Lần đầu nghĩa là không có khoản trừ cùng loại còn lưu trước thời điểm hoặc tháng đã chọn; khoản trừ trước đầu khoảng, dù cùng tháng, được tính là lặp lại. Khoản trừ có thể ghi khi đang cấp thưởng rồi được hoàn bù, nên không chứng minh phát hành hay sử dụng thành công. Không thể khôi phục lịch sử đã xóa, trước Weletic hoặc hợp nhất nhiều tài khoản; đây không phải nhóm khách hàng theo toàn bộ vòng đời.",
  debitAccounts: "Tài khoản có khoản trừ đã ghi",
  firstRecordedDebitAccounts: "Tài khoản ghi nhận trừ điểm lần đầu",
  returningDebitAccounts: "Tài khoản ghi nhận trừ điểm lặp lại",
  retainedEnrollmentSeries: "Tài khoản còn lưu theo thời điểm đăng ký (UTC)",
  retainedEnrollmentOpening: "Tài khoản còn lưu trước khoảng đã chọn",
  retainedEnrollmentSemantics:
    "Đếm các tài khoản Loyalty hiện còn lưu theo thời điểm đăng ký đã ghi. Tổng lũy kế cộng số đăng ký trong từng tháng UTC thuộc khoảng đã chọn vào số tài khoản đăng ký trước lúc bắt đầu; tháng đầu và cuối có thể chỉ gồm một phần. Không thể khôi phục tài khoản đã xóa hoặc lịch sử trước Weletic. Đây không phải số hội viên hoạt động trong quá khứ hay tổng khách hàng Shopify.",
  openingRetainedAccounts: "Tài khoản còn lưu trước khoảng chọn",
  newRetainedAccounts: "Đăng ký mới đã ghi",
  cumulativeRetainedAccounts: "Lũy kế tài khoản còn lưu",
  earningSources: "Nguồn tích điểm đã ghi nhận",
  earningSourcesSemantics:
    "Xếp hạng các bút toán tích điểm dương còn lưu theo tổng điểm trong khoảng thời gian đã chọn. Số lượt là số bút toán, không phải số khách hay đơn hàng. Hoàn tiền sau đó được ghi riêng nên đây không phải điểm ròng hoặc toàn bộ vòng đời cửa hàng. Loại trừ điểm nhập lịch sử và điều chỉnh thủ công; lịch sử thiếu hoặc đã xóa không khả dụng.",
  entryType: "Nguồn tích điểm",
  redemptionSources: "Nguồn đổi thưởng đã ghi theo điểm trừ",
  redemptionSourcesTotal: "Tổng bút toán trừ điểm đổi thưởng",
  redemptionSourcesSemantics:
    "Xếp hạng bút toán trừ điểm đổi thưởng còn lưu theo tổng điểm trong khoảng đã chọn. Tên và loại được ghi lúc trừ điểm; bản ghi đổi thưởng liên kết chỉ xác nhận ID phần thưởng và số điểm. Thông tin thiếu hoặc không khớp thuộc nhóm Không rõ; các nhóm ngoài mười vị trí đầu thuộc Khác. Đây là lượt trừ điểm, không phải lượt dùng giảm giá thực tế hay chi phí ròng. Hủy và hoàn tiền được ghi riêng. Không gồm phần thưởng trực tiếp không tốn điểm hoặc lịch sử thiếu, đã xóa.",
  group: "Nhóm nguồn gốc",
  recordedReward: "Phần thưởng đã ghi",
  otherRewards: "Phần thưởng khác đã ghi",
  unknownReward: "Không rõ nguồn gốc",
  rewardDefinitionId: "ID định nghĩa phần thưởng",
  capturedName: "Tên lúc trừ điểm",
  rewardType: "Loại phần thưởng",
  redemptionEvents: "Số lượt trừ điểm đã ghi",
  grossRedemptionPoints: "Tổng điểm đã trừ",
  amount_off: "Giảm số tiền cố định",
  percentage_off: "Giảm theo phần trăm",
  free_shipping: "Miễn phí vận chuyển",
  free_product: "Sản phẩm miễn phí",
  eventCount: "Số lượt tích điểm đã ghi",
  pointsEarned: "Tổng điểm tích lũy gộp",
  EARN_ORDER: "Đơn hàng",
  EARN_REFERRAL: "Giới thiệu",
  EARN_BONUS: "Thưởng",
  TIER_BONUS: "Thưởng hạng VIP",
  activeAccounts: "Tài khoản có tích điểm",
  firstRecordedAccounts: "Tài khoản tích điểm lần đầu ghi nhận",
  returningAccounts: "Tài khoản quay lại tích điểm",
  recordedTierChangesSeries: "Sự kiện hạng VIP đã ghi theo lý do (UTC)",
  recordedTierChangesSemantics:
    "Đếm sự kiện trong lịch sử hạng còn lưu theo lý do đã ghi ở mỗi tháng UTC. Tháng đầu và cuối có thể chỉ gồm một phần thời gian. Lý do không chứng minh hướng tăng hoặc giảm hạng, thành viên hạng trong quá khứ hay lịch sử thiếu hoặc đã xóa. Sự kiện nhập và thao tác thủ công vẫn nằm trong nhóm lý do được ghi.",
  totalChanges: "Sự kiện hạng đã ghi",
  thresholdReached: "Đạt ngưỡng",
  bonusPromotion: "Lý do thưởng nâng hạng",
  annualDowngrade: "Lý do giảm hạng hằng năm",
  gracePeriodExpired: "Hết thời gian gia hạn",
  programActivation: "Kích hoạt chương trình",
  manualOverride: "Điều chỉnh thủ công",
  otherReasons: "Lý do đã ghi khác",
  ledgerNetOpening: "Biến động ròng đã ghi trước khoảng chọn",
  ledgerNetSemantics:
    "Đây là tổng có dấu của các bút toán điểm còn lưu trước và trong khoảng thời gian đã chọn. Ngày UTC đầu và cuối có thể chỉ được tính một phần. Chỉ số này không phải nghĩa vụ điểm còn tồn trong quá khứ vì không khôi phục lịch sử trước Weletic hoặc khoản nợ theo từng tài khoản.",
  openingNetPoints: "Điểm ròng đã ghi trước khoảng chọn",
  netChangePoints: "Thay đổi ròng theo ngày",
  cumulativeNetPoints: "Biến động ròng tích lũy đã ghi",
  redemptionRateSeries: "Tỷ lệ dùng điểm trên điểm tích lũy theo tháng (UTC)",
  redemptionRateSemantics:
    "Trong khoảng thời gian đã chọn của từng tháng UTC, điểm đã dùng đổi thưởng được chia cho điểm đã tích lũy theo sổ điểm; tháng đầu và cuối có thể chỉ gồm một phần tháng. Mẫu số không gồm điểm bổ sung lịch sử; hoàn điểm, hết hạn và điều chỉnh thủ công được tách riêng. Điểm đã dùng ban đầu của thưởng bị hủy vẫn được tính; điểm trả lại nằm trong điều chỉnh thủ công. Tỷ lệ có thể vượt 100% khi dùng điểm tích lũy từ trước. Tháng không có điểm tích lũy đủ điều kiện thì không có tỷ lệ. Đây không phải tỷ lệ sử dụng mã giảm giá hay chỉ số của toàn cửa hàng.",
  month: "Tháng UTC",
  earnedPoints: "Điểm tích lũy, không gồm bổ sung lịch sử",
  redeemedPoints: "Điểm đã dùng đổi thưởng",
  redemptionRateBasisPoints: "Tỷ lệ dùng điểm trên điểm tích lũy",
  orderEarningSeries: "Tỷ lệ tích điểm của đơn đã ghi nhận (UTC)",
  orderEarningSemantics:
    "Chỉ tính các đơn hàng Weletic đã ghi nhận, gồm cả đơn đang chờ và đã vô hiệu, theo thời điểm đặt hàng. Đơn có khoản cấp điểm mua hàng dương được tính một lần, kể cả điểm bổ sung lịch sử hoặc bị thu hồi sau đó; đây không phải số điểm còn giữ. Đơn Shopify chưa ghi nhận nằm ngoài báo cáo, nên đây không phải tỷ lệ của toàn cửa hàng.",
  recordedOrders: "Đơn hàng đã ghi nhận",
  earningOrders: "Đơn có khoản cấp điểm dương",
  rateBasisPoints: "Tỷ lệ tích điểm",
  range_required: "Chọn cả hai ngày để xem tối đa 366 ngày UTC.",
  range_too_wide: "Chọn khoảng thời gian không quá 366 ngày UTC.",
  date: "Ngày UTC",
  referralEconomics: "Doanh thu và chi phí giới thiệu",
  referrals: "Nhóm trạng thái giới thiệu",
  rewards: "Sử dụng phần thưởng",
  tiers: "Phân bố VIP",
  currency: "Tiền tệ kế toán",
  generated: "Thời điểm tổng hợp",
  status: "Trạng thái",
  artifact: "Loại phần thưởng",
  count: "Số lượng",
  pointsSpent: "Điểm đã dùng",
  name: "Hạng",
  members: "Thành viên",
  pointsBalance: "Số dư điểm dương",
  rollingSpendMinorUnits: "Chi tiêu trong kỳ (đơn vị nhỏ nhất)",
  circulatingPoints: "Điểm đang lưu hành",
  pendingPoints: "Điểm đang chờ",
  debtPoints: "Nợ điểm do số dư âm",
  currentMinorUnits: "Nghĩa vụ hiện tại (đơn vị nhỏ nhất)",
  pendingMinorUnits: "Nghĩa vụ đang chờ (đơn vị nhỏ nhất)",
  potentialMinorUnits: "Nghĩa vụ tiềm năng (đơn vị nhỏ nhất)",
  totalMembers: "Tổng thành viên",
  activeMembers: "Thành viên hoạt động (90 ngày)",
  earned: "Điểm đã tích (gồm bổ sung lịch sử)",
  redeemed: "Điểm đã đổi",
  refundReversed: "Điểm thu hồi do hoàn tiền",
  expired: "Điểm hết hạn",
  backfilled: "Điểm bổ sung lịch sử",
  backfillCorrected: "Điều chỉnh bổ sung lịch sử",
  manualCredits: "Cộng điểm thủ công",
  manualDebits: "Trừ điểm thủ công",
  total: "Tổng lượt giới thiệu",
  successful: "Giới thiệu thành công",
  revenueMinorUnits: "Doanh thu (đơn vị nhỏ nhất)",
  costMinorUnits: "Chi phí phần thưởng (đơn vị nhỏ nhất)",
  pending: "Đang chờ",
  qualified: "Đủ điều kiện",
  rewarded: "Đã thưởng",
  cancelled: "Đã hủy",
  fraud_blocked: "Bị chặn do gian lận",
  active: "Đang hoạt động",
  provisioning: "Đang cấp",
  issued: "Đã cấp",
  used: "Đã sử dụng",
  failed: "Thất bại",
  discount_code: "Mã giảm giá",
  gift_card: "Thẻ quà tặng",
  store_credit: "Tín dụng cửa hàng",
};
export const merchantAnalyticsCopy = { en, ja, vi };
