const en = {
  expiredStatus: "Expired",
  unassigned: "Unassigned",
  title: "Loyalty analytics",
  language: "Language",
  start: "Start date (UTC)",
  end: "End date (UTC)",
  refresh: "Apply dates",
  loading: "Loading analytics…",
  error: "Analytics unavailable. Check your access and try again.",
  invalid: "Choose a valid date range.",
  unavailable: "Unavailable",
  empty: "No matching activity",
  csv: "Export CSV",
  json: "Export JSON",
  exportNote: "Financial exports are available to the store owner only.",
  semantics:
    "Balances and VIP distribution are current snapshots. Point activity uses the selected date range. Reward and referral statuses describe records created in that range, not a sequence of completed funnel steps. Empty dates include all history. Monetary values are exact minor units of the displayed currency (for example, cents for USD; yen for JPY).",
  financial:
    "Some financial metrics are unavailable. A valid valuation and reconciled order currencies are required. Unavailable values are not zero.",
  liability: "Current balances and liability",
  activity: "Point activity",
  activitySeries: "Daily point activity (UTC)",
  ledgerNetSeries: "Recorded ledger net over time (UTC)",
  ledgerNetOpening: "Recorded net before the selected range",
  ledgerNetSemantics:
    "This is the signed sum of retained point-ledger entries before and within the selected instants. The first and last UTC days may be partial. It is not historical outstanding liability: missing pre-Weletic history and account-level debt are not reconstructed.",
  openingNetPoints: "Opening recorded net points",
  netChangePoints: "Daily net change",
  cumulativeNetPoints: "Cumulative recorded net",
  redemptionRateSeries: "Monthly redemption-to-earn rate (UTC)",
  redemptionRateSemantics:
    "Within the selected interval in each UTC month, recorded reward-spend points are divided by recorded earned points; boundary months may be partial. Earned points exclude backfills; refund reversals, expiry and manual adjustments stay separate. Canceled rewards remain in gross spend while restoration credits stay in manual adjustments. Spending earlier earnings can make this rate exceed 100%. A month with no qualifying earned points has no rate. This is not discount usage or a whole-store measure.",
  month: "UTC month",
  earnedPoints: "Earned points, excluding backfill",
  redeemedPoints: "Reward-spend points",
  redemptionRateBasisPoints: "Redemption-to-earn rate",
  orderEarningSeries: "Recorded order earning rate (UTC)",
  orderEarningSemantics:
    "Only orders recorded by Weletic are counted, including pending and voided records. Dates use the order timestamp. A positive recorded purchase-points grant counts once, including backfills and later-refunded grants; this is not a measure of points still held. Missing Shopify orders are outside this report, so it does not establish a whole-store rate.",
  recordedOrders: "Recorded orders",
  earningOrders: "Orders with positive points grant",
  rateBasisPoints: "Earning rate",
  range_required: "Select both dates to view up to 366 UTC days.",
  range_too_wide: "Choose a range of at most 366 UTC days.",
  date: "UTC date",
  referralEconomics: "Referral economics",
  referrals: "Referral status cohorts",
  rewards: "Reward utilization",
  tiers: "VIP distribution",
  currency: "Accounting currency",
  generated: "Generated at",
  status: "Status",
  artifact: "Artifact",
  count: "Count",
  pointsSpent: "Points spent",
  name: "Tier",
  members: "Members",
  pointsBalance: "Positive points balance",
  rollingSpendMinorUnits: "Rolling spend (minor units)",
  circulatingPoints: "Circulating points",
  pendingPoints: "Pending points",
  debtPoints: "Negative-balance debt points",
  currentMinorUnits: "Current liability (minor units)",
  pendingMinorUnits: "Pending liability (minor units)",
  potentialMinorUnits: "Potential liability (minor units)",
  totalMembers: "Total members",
  activeMembers: "Active members (90 days)",
  earned: "Earned points (includes backfill)",
  redeemed: "Redeemed points",
  refundReversed: "Refund-reversed points",
  expired: "Expired points",
  backfilled: "Backfilled points",
  backfillCorrected: "Backfill corrections",
  manualCredits: "Manual credits",
  manualDebits: "Manual debits",
  total: "Total referrals",
  successful: "Successful referrals",
  revenueMinorUnits: "Revenue (minor units)",
  costMinorUnits: "Reward cost (minor units)",
  pending: "Pending",
  qualified: "Qualified",
  rewarded: "Rewarded",
  cancelled: "Cancelled",
  fraud_blocked: "Fraud blocked",
  active: "Active",
  provisioning: "Provisioning",
  issued: "Issued",
  used: "Used",
  failed: "Failed",
  discount_code: "Discount code",
  gift_card: "Gift card",
  store_credit: "Store credit",
};
type Copy = Record<keyof typeof en, string>;
const ja: Copy = {
  expiredStatus: "期限切れ",
  unassigned: "未設定",
  title: "ロイヤルティ分析",
  language: "言語",
  start: "開始日（UTC）",
  end: "終了日（UTC）",
  refresh: "期間を適用",
  loading: "分析を読み込み中…",
  error: "分析を取得できません。アクセス権を確認して再試行してください。",
  invalid: "有効な期間を選択してください。",
  unavailable: "利用不可",
  empty: "該当する履歴はありません",
  csv: "CSVを出力",
  json: "JSONを出力",
  exportNote: "財務データの出力はストアオーナーのみ利用できます。",
  semantics:
    "残高とVIP分布は現在の状態です。ポイント履歴には選択した期間を適用します。特典と紹介のステータスは、その期間に作成された記録の現在の状態であり、順番に完了したファネルの段階ではありません。日付が空欄の場合は全期間です。金額は表示通貨の最小単位の正確な値です（USDはセント、JPYは円）。",
  financial:
    "一部の財務指標は利用できません。有効なポイント評価と注文通貨の照合が必要です。利用不可はゼロを意味しません。",
  liability: "現在の残高と負債",
  activity: "ポイント履歴",
  activitySeries: "日別ポイント履歴（UTC）",
  ledgerNetSeries: "記録済み台帳の累積純増減（UTC）",
  ledgerNetOpening: "選択期間前の記録済み純増減",
  ledgerNetSemantics:
    "保存されたポイント台帳の増減を、選択した期間の前と期間内で合計します。期間の最初と最後のUTC日は一部のみを含む場合があります。Weletic導入前の履歴や会員ごとのマイナス残高は復元していないため、過去の未履行債務を示すものではありません。",
  openingNetPoints: "開始前の記録済み純増減ポイント",
  netChangePoints: "日別の純増減",
  cumulativeNetPoints: "記録済み累積純増減",
  redemptionRateSeries: "月別ポイント利用・獲得比率（UTC）",
  redemptionRateSemantics:
    "選択した期間内の各UTC月に記録された特典交換の使用ポイントを、同じ期間の獲得ポイントで割った比率です。期間の端にある月は一部の日付のみを含む場合があります。獲得ポイントに過去分補填は含めず、返金による取戻し、失効、手動調整は別に扱います。取り消された特典の元の使用ポイントは残り、返還分は手動調整に分けて記録されます。以前に獲得したポイントを使うと100%を超える場合があります。対象の獲得がない月は比率を表示しません。割引の利用率やストア全体の指標ではありません。",
  month: "UTC月",
  earnedPoints: "獲得ポイント（過去分補填を除く）",
  redeemedPoints: "特典交換の使用ポイント",
  redemptionRateBasisPoints: "ポイント利用・獲得比率",
  orderEarningSeries: "記録済み注文のポイント獲得率（UTC）",
  orderEarningSemantics:
    "Weleticに記録された注文のみを集計し、保留中と無効の注文も含めます。日付は注文日時です。正の購入ポイント付与が記録された注文は、過去分補填や後で返金された付与も1件として数えます。現在保有するポイント数の指標ではありません。記録のない注文は含まれないため、ストア全体の獲得率は示しません。",
  recordedOrders: "記録済み注文",
  earningOrders: "正のポイント付与がある注文",
  rateBasisPoints: "獲得率",
  range_required: "両方の日付を選択すると、最大366日間を表示できます。",
  range_too_wide: "366日以内の期間を選択してください。",
  date: "UTCの日付",
  referralEconomics: "紹介の収益と費用",
  referrals: "紹介のステータス別集計",
  rewards: "特典の利用状況",
  tiers: "VIP分布",
  currency: "会計通貨",
  generated: "生成日時",
  status: "ステータス",
  artifact: "特典形式",
  count: "件数",
  pointsSpent: "使用ポイント",
  name: "ランク",
  members: "会員数",
  pointsBalance: "正のポイント残高",
  rollingSpendMinorUnits: "期間内購入額（最小通貨単位）",
  circulatingPoints: "流通ポイント",
  pendingPoints: "保留ポイント",
  debtPoints: "マイナス残高の債務ポイント",
  currentMinorUnits: "現在の負債（最小通貨単位）",
  pendingMinorUnits: "保留分の負債（最小通貨単位）",
  potentialMinorUnits: "潜在負債（最小通貨単位）",
  totalMembers: "総会員数",
  activeMembers: "アクティブ会員（90日）",
  earned: "獲得ポイント（過去分補填を含む）",
  redeemed: "利用ポイント",
  refundReversed: "返金に伴う取消ポイント",
  expired: "失効ポイント",
  backfilled: "過去分補填ポイント",
  backfillCorrected: "過去分補填の修正",
  manualCredits: "手動加算",
  manualDebits: "手動減算",
  total: "紹介総数",
  successful: "成功した紹介",
  revenueMinorUnits: "売上（最小通貨単位）",
  costMinorUnits: "特典費用（最小通貨単位）",
  pending: "保留",
  qualified: "条件達成",
  rewarded: "付与済み",
  cancelled: "取消済み",
  fraud_blocked: "不正防止による停止",
  active: "有効",
  provisioning: "発行処理中",
  issued: "発行済み",
  used: "使用済み",
  failed: "失敗",
  discount_code: "割引コード",
  gift_card: "ギフトカード",
  store_credit: "ストアクレジット",
};
const vi: Copy = {
  expiredStatus: "Đã hết hạn",
  unassigned: "Chưa phân hạng",
  title: "Phân tích khách hàng thân thiết",
  language: "Ngôn ngữ",
  start: "Ngày bắt đầu (UTC)",
  end: "Ngày kết thúc (UTC)",
  refresh: "Áp dụng ngày",
  loading: "Đang tải phân tích…",
  error: "Không thể tải phân tích. Hãy kiểm tra quyền truy cập và thử lại.",
  invalid: "Chọn khoảng ngày hợp lệ.",
  unavailable: "Không khả dụng",
  empty: "Không có hoạt động phù hợp",
  csv: "Xuất CSV",
  json: "Xuất JSON",
  exportNote: "Chỉ chủ cửa hàng có quyền xuất dữ liệu tài chính.",
  semantics:
    "Số dư và phân bố VIP phản ánh trạng thái hiện tại. Hoạt động điểm được lọc theo khoảng ngày đã chọn. Trạng thái phần thưởng và giới thiệu phản ánh các bản ghi được tạo trong khoảng đó, không phải các bước liên tiếp đã hoàn thành. Để trống ngày để xem toàn bộ lịch sử. Giá trị tiền là số chính xác theo đơn vị nhỏ nhất của đồng tiền hiển thị (ví dụ: cent với USD, yên với JPY).",
  financial:
    "Một số chỉ số tài chính chưa khả dụng. Cần định giá điểm hợp lệ và đối soát tiền tệ đơn hàng. Không khả dụng không có nghĩa là bằng không.",
  liability: "Số dư và nghĩa vụ hiện tại",
  activity: "Hoạt động điểm",
  activitySeries: "Hoạt động điểm theo ngày (UTC)",
  ledgerNetSeries: "Biến động ròng tích lũy theo sổ điểm (UTC)",
  ledgerNetOpening: "Biến động ròng đã ghi trước khoảng chọn",
  ledgerNetSemantics:
    "Đây là tổng có dấu của các bút toán điểm còn lưu trước và trong khoảng thời gian đã chọn. Ngày UTC đầu và cuối có thể chỉ được tính một phần. Chỉ số này không phải nghĩa vụ điểm còn tồn trong quá khứ vì không khôi phục lịch sử trước Weletic hoặc khoản nợ theo từng tài khoản.",
  openingNetPoints: "Điểm ròng đã ghi trước khoảng chọn",
  netChangePoints: "Thay đổi ròng theo ngày",
  cumulativeNetPoints: "Biến động ròng tích lũy đã ghi",
  redemptionRateSeries: "Tỷ lệ dùng điểm trên điểm tích lũy theo tháng (UTC)",
  redemptionRateSemantics:
    "Trong khoảng thời gian đã chọn của từng tháng UTC, điểm đã dùng đổi thưởng được chia cho điểm đã tích lũy theo sổ điểm; tháng đầu và cuối có thể chỉ gồm một phần tháng. Mẫu số không gồm điểm bổ sung lịch sử; hoàn điểm, hết hạn và điều chỉnh thủ công được tách riêng. Điểm đã dùng ban đầu của thưởng bị hủy vẫn được tính; điểm trả lại nằm trong điều chỉnh thủ công. Tỷ lệ có thể vượt 100% khi dùng điểm tích lũy từ trước. Tháng không có điểm tích lũy đủ điều kiện thì không có tỷ lệ. Đây không phải tỷ lệ sử dụng mã giảm giá hay chỉ số của toàn cửa hàng.",
  month: "Tháng UTC",
  earnedPoints: "Điểm tích lũy, không gồm bổ sung lịch sử",
  redeemedPoints: "Điểm đã dùng đổi thưởng",
  redemptionRateBasisPoints: "Tỷ lệ dùng điểm trên điểm tích lũy",
  orderEarningSeries: "Tỷ lệ tích điểm của đơn đã ghi nhận (UTC)",
  orderEarningSemantics:
    "Chỉ tính các đơn hàng Weletic đã ghi nhận, gồm cả đơn đang chờ và đã vô hiệu, theo thời điểm đặt hàng. Đơn có khoản cấp điểm mua hàng dương được tính một lần, kể cả điểm bổ sung lịch sử hoặc bị thu hồi sau đó; đây không phải số điểm còn giữ. Đơn Shopify chưa ghi nhận nằm ngoài báo cáo, nên đây không phải tỷ lệ của toàn cửa hàng.",
  recordedOrders: "Đơn hàng đã ghi nhận",
  earningOrders: "Đơn có khoản cấp điểm dương",
  rateBasisPoints: "Tỷ lệ tích điểm",
  range_required: "Chọn cả hai ngày để xem tối đa 366 ngày UTC.",
  range_too_wide: "Chọn khoảng thời gian không quá 366 ngày UTC.",
  date: "Ngày UTC",
  referralEconomics: "Doanh thu và chi phí giới thiệu",
  referrals: "Nhóm trạng thái giới thiệu",
  rewards: "Sử dụng phần thưởng",
  tiers: "Phân bố VIP",
  currency: "Tiền tệ kế toán",
  generated: "Thời điểm tổng hợp",
  status: "Trạng thái",
  artifact: "Loại phần thưởng",
  count: "Số lượng",
  pointsSpent: "Điểm đã dùng",
  name: "Hạng",
  members: "Thành viên",
  pointsBalance: "Số dư điểm dương",
  rollingSpendMinorUnits: "Chi tiêu trong kỳ (đơn vị nhỏ nhất)",
  circulatingPoints: "Điểm đang lưu hành",
  pendingPoints: "Điểm đang chờ",
  debtPoints: "Nợ điểm do số dư âm",
  currentMinorUnits: "Nghĩa vụ hiện tại (đơn vị nhỏ nhất)",
  pendingMinorUnits: "Nghĩa vụ đang chờ (đơn vị nhỏ nhất)",
  potentialMinorUnits: "Nghĩa vụ tiềm năng (đơn vị nhỏ nhất)",
  totalMembers: "Tổng thành viên",
  activeMembers: "Thành viên hoạt động (90 ngày)",
  earned: "Điểm đã tích (gồm bổ sung lịch sử)",
  redeemed: "Điểm đã đổi",
  refundReversed: "Điểm thu hồi do hoàn tiền",
  expired: "Điểm hết hạn",
  backfilled: "Điểm bổ sung lịch sử",
  backfillCorrected: "Điều chỉnh bổ sung lịch sử",
  manualCredits: "Cộng điểm thủ công",
  manualDebits: "Trừ điểm thủ công",
  total: "Tổng lượt giới thiệu",
  successful: "Giới thiệu thành công",
  revenueMinorUnits: "Doanh thu (đơn vị nhỏ nhất)",
  costMinorUnits: "Chi phí phần thưởng (đơn vị nhỏ nhất)",
  pending: "Đang chờ",
  qualified: "Đủ điều kiện",
  rewarded: "Đã thưởng",
  cancelled: "Đã hủy",
  fraud_blocked: "Bị chặn do gian lận",
  active: "Đang hoạt động",
  provisioning: "Đang cấp",
  issued: "Đã cấp",
  used: "Đã sử dụng",
  failed: "Thất bại",
  discount_code: "Mã giảm giá",
  gift_card: "Thẻ quà tặng",
  store_credit: "Tín dụng cửa hàng",
};
export const merchantAnalyticsCopy = { en, ja, vi };
