export const nudgeCopy = {
  en: {
    title: "Storefront nudges",
    language: "Editor language",
    contentLanguage: "Message language",
    kind: "Nudge",
    enabled: "Enable this nudge",
    icon: "Icon",
    subject: "Title",
    description: "Description",
    actionLabel: "Button label",
    save: "Save all nudges and languages",
    discard: "Discard changes",
    reload: "Reload and discard draft",
    restore: "Restore this nudge's default copy",
    loading: "Loading…",
    saved: "Configuration saved. No redemption or email was triggered.",
    error: "Unable to confirm the latest state. Reload before saving again.",
    invalid: "Check text lengths and allowed variables.",
    readonly: "You can view these settings but cannot edit them.",
    missing: "Set up the loyalty program before configuring nudges.",
    preview: "Sample preview — no customer data",
    note: "Nudges require the compatible storefront runtime. Cart prompts appear on cart pages, not cart drawers. Gift cards, store credit and variable rewards are excluded. Uploaded icons are not supported by this draft.",
    leave: "Discard unsaved nudge changes and leave this page?",
    signup: "Account creation",
    points_spending: "Points spending",
    reward_usage: "Reward usage",
    gift: "Gift",
    star: "Star",
    award: "Award",
    sparkles: "Sparkles",
  },
  ja: {
    title: "ストアフロント通知",
    language: "編集画面の言語",
    contentLanguage: "メッセージの言語",
    kind: "通知",
    enabled: "この通知を有効にする",
    icon: "アイコン",
    subject: "タイトル",
    description: "説明",
    actionLabel: "ボタンの文言",
    save: "すべての通知と言語を保存",
    discard: "変更を破棄",
    reload: "再読み込みして下書きを破棄",
    restore: "この通知の既定文言に戻す",
    loading: "読み込み中…",
    saved: "設定を保存しました。特典交換やメール送信は行っていません。",
    error: "最新の状態を確認できません。再読み込みしてから保存してください。",
    invalid: "文字数と使用できる変数を確認してください。",
    readonly: "閲覧できますが、変更する権限がありません。",
    missing: "通知を設定する前にロイヤルティプログラムを設定してください。",
    preview: "サンプルプレビュー — 顧客データなし",
    note: "対応するストアフロントが必要です。カート通知はカートページ専用で、カートドロワーには表示されません。ギフトカード、ストアクレジット、可変特典は対象外です。この下書きではアイコンのアップロードは未対応です。",
    leave: "通知の未保存の変更を破棄して、このページを離れますか？",
    signup: "アカウント登録",
    points_spending: "ポイント利用",
    reward_usage: "特典利用",
    gift: "ギフト",
    star: "星",
    award: "表彰",
    sparkles: "きらめき",
  },
  vi: {
    title: "Thông báo trên cửa hàng",
    language: "Ngôn ngữ trình chỉnh sửa",
    contentLanguage: "Ngôn ngữ nội dung",
    kind: "Loại thông báo",
    enabled: "Bật thông báo này",
    icon: "Biểu tượng",
    subject: "Tiêu đề",
    description: "Mô tả",
    actionLabel: "Nhãn nút",
    save: "Lưu tất cả thông báo và ngôn ngữ",
    discard: "Bỏ thay đổi",
    reload: "Tải lại và bỏ bản nháp",
    restore: "Khôi phục nội dung mặc định của thông báo này",
    loading: "Đang tải…",
    saved: "Đã lưu cấu hình. Không đổi thưởng hoặc gửi email.",
    error:
      "Không thể xác nhận trạng thái mới nhất. Hãy tải lại trước khi lưu tiếp.",
    invalid: "Kiểm tra độ dài nội dung và các biến được phép.",
    readonly: "Bạn có thể xem nhưng không có quyền chỉnh sửa.",
    missing:
      "Thiết lập chương trình khách hàng thân thiết trước khi cấu hình thông báo.",
    preview: "Xem trước mẫu — không có dữ liệu khách hàng",
    note: "Cần giao diện cửa hàng tương thích. Thông báo giỏ hàng chỉ hiện trên trang giỏ hàng, không phải ngăn giỏ hàng. Không áp dụng cho thẻ quà tặng, tín dụng cửa hàng và phần thưởng biến đổi. Bản nháp chưa hỗ trợ tải biểu tượng lên.",
    leave: "Bỏ thay đổi thông báo chưa lưu và rời trang này?",
    signup: "Tạo tài khoản",
    points_spending: "Sử dụng điểm",
    reward_usage: "Sử dụng phần thưởng",
    gift: "Quà tặng",
    star: "Ngôi sao",
    award: "Giải thưởng",
    sparkles: "Lấp lánh",
  },
};
