import { nanoid } from "@dub/utils";

export type WeleticIdPrefix =
  | "wstore_"
  | "wmarket_"
  | "wprod_"
  | "wvar_"
  | "wtrans_"
  | "wprice_"
  | "wsync_"
  | "whook_"
  | "wplink_"
  | "wfx_"
  | "worder_"
  | "wline_"
  | "wrefund_"
  | "wrline_"
  | "wrule_"
  | "wcalc_"
  | "wprofile_"
  | "wquote_"
  | "wstatement_"
  | "wrecon_"
  | "wshop_"
  | "wlprog_"
  | "wprog_"
  | "wlacc_"
  | "wacc_"
  | "wintent_"
  | "wledger_"
  | "wreward_"
  | "wredemp_"
  | "wrcu_"
  | "wreferral_"
  | "wreviewint_"
  | "wreview_"
  | "wrevreq_"
  | "wrevline_"
  | "wrevmedia_"
  | "wrevpolicy_"
  | "wrevclaim_"
  | "wrevinv_"
  | "wrevaudit_"
  | "wtier_"
  | "wcamp_"
  | "wpolicy_"
  | "wbackfill_"
  | "wlimp_"
  | "wlimpr_"
  | "wbfsnap_"
  | "wbfcredit_"
  | "wlineearn_"
  | "wlease_"
  | "woutbox_"
  | "wflow_"
  | "wcomp_"
  | "wartifact_"
  | "wtomb_"
  | "wvclean_"
  | "wvclink_"
  | "wgrant_"
  | "sgen_";

export const createWeleticId = (prefix: WeleticIdPrefix) =>
  `${prefix}${nanoid(20)}`;
