const en = {
  title: "Loyalty launcher and panel",
  language: "Editor language",
  save: "Save loyalty appearance",
  reload: "Reload saved appearance",
  loading: "Loading…",
  saved: "Loyalty appearance saved.",
  error: "Appearance could not be verified. Reload before trying again.",
  invalid: "Check the appearance fields before saving.",
  missing: "Configure the loyalty program before editing its appearance.",
  discard: "Discard unsaved appearance changes?",
  note: "Customize the launcher, device layouts and panel without activating loyalty. Nudge policies are managed separately.",
  launcherText: "Launcher label",
  launcherPosition: "Launcher position",
  launcherIcon: "Launcher icon",
  primaryColor: "Primary color (#RRGGBB)",
  headerTextColor: "Header text color (#RRGGBB)",
  panelTitle: "Panel title",
  panelWelcomeSubtitle: "Welcome subtitle",
  heroImageUrl: "Public HTTPS hero image URL (optional)",
  enableFloatingLauncher: "Show floating launcher",
  bottom_right: "Bottom right",
  bottom_left: "Bottom left",
  award: "Award",
  gift: "Gift",
  crown: "Crown",
  star: "Star",
  sparkles: "Sparkles",
};
type Copy = Record<keyof typeof en, string>;
export const appearanceCopy: Record<"en" | "ja" | "vi", Copy> = {
  en,
  ja: {
    title: "ロイヤルティのランチャーとパネル",
    language: "編集画面の言語",
    save: "ロイヤルティの外観を保存",
    reload: "保存済みの外観を再読み込み",
    loading: "読み込み中…",
    saved: "ロイヤルティの外観を保存しました。",
    error: "外観を確認できませんでした。再読み込みしてからお試しください。",
    invalid: "保存する前に入力内容を確認してください。",
    missing: "外観を編集する前にロイヤルティプログラムを設定してください。",
    discard: "未保存の外観変更を破棄しますか？",
    note: "ランチャー、デバイス別レイアウトとパネルをカスタマイズします。ロイヤルティは有効化されません。ナッジは別画面で管理します。",
    launcherText: "ランチャーのラベル",
    launcherPosition: "ランチャーの位置",
    launcherIcon: "ランチャーのアイコン",
    primaryColor: "メインカラー（#RRGGBB）",
    headerTextColor: "ヘッダーの文字色（#RRGGBB）",
    panelTitle: "パネルのタイトル",
    panelWelcomeSubtitle: "ウェルカムサブタイトル",
    heroImageUrl: "公開HTTPSヒーロー画像URL（任意）",
    enableFloatingLauncher: "フローティングランチャーを表示",
    bottom_right: "右下",
    bottom_left: "左下",
    award: "アワード",
    gift: "ギフト",
    crown: "王冠",
    star: "星",
    sparkles: "きらめき",
  },
  vi: {
    title: "Nút mở và bảng loyalty",
    language: "Ngôn ngữ trình chỉnh sửa",
    save: "Lưu giao diện loyalty",
    reload: "Tải lại giao diện đã lưu",
    loading: "Đang tải…",
    saved: "Đã lưu giao diện loyalty.",
    error: "Không thể xác minh giao diện. Hãy tải lại trước khi thử tiếp.",
    invalid: "Kiểm tra các trường giao diện trước khi lưu.",
    missing: "Hãy cấu hình chương trình loyalty trước khi chỉnh sửa giao diện.",
    discard: "Bỏ các thay đổi giao diện chưa lưu?",
    note: "Tùy chỉnh nút mở, bố cục theo thiết bị và bảng mà không kích hoạt loyalty. Chính sách lời nhắc được quản lý riêng.",
    launcherText: "Nhãn nút mở",
    launcherPosition: "Vị trí nút mở",
    launcherIcon: "Biểu tượng nút mở",
    primaryColor: "Màu chính (#RRGGBB)",
    headerTextColor: "Màu chữ tiêu đề (#RRGGBB)",
    panelTitle: "Tiêu đề bảng",
    panelWelcomeSubtitle: "Dòng chào mừng",
    heroImageUrl: "URL HTTPS công khai của ảnh đầu bảng (tùy chọn)",
    enableFloatingLauncher: "Hiển thị nút mở nổi",
    bottom_right: "Góc dưới bên phải",
    bottom_left: "Góc dưới bên trái",
    award: "Huy hiệu",
    gift: "Quà tặng",
    crown: "Vương miện",
    star: "Ngôi sao",
    sparkles: "Lấp lánh",
  },
};
