export const flowGrantsCopy = {
  en: {
    title: "Shopify Flow points authority",
    language: "Language",
    intro:
      "Owner-only. Grants authorize bounded manual point adjustments, not purchases or review incentives. Grant status does not mean Flow is deployed or enabled.",
    loading: "Checking owner access…",
    unavailable:
      "Access or data unavailable. Reopen the app to authenticate if needed.",
    uncertain:
      "The write result is uncertain. Do not submit again or reload this page. Check the original attempt below.",
    check: "Check original attempt",
    unresolved:
      "No conclusive result yet. Authority remains unchanged locally; do not repeat the write.",
    saved: "Confirmed by the server.",
    invalid:
      "Select a direction, exact positive limits, a future expiry and confirm authorization.",
    credit: "Allow adding points",
    debit: "Allow removing points",
    maximum: "Maximum absolute points per action",
    budget: "Total absolute points budget",
    expires: "Expiry (your local time)",
    consent:
      "I authorize these limits for company workflows. Debits may create a negative balance.",
    create: "Authorize grant",
    reload: "Refresh",
    next: "Next page",
    first: "First page",
    revoke: "Revoke",
    confirm: "Confirm revocation",
    cancel: "Cancel",
    empty: "No grants on this page.",
    remaining: "Remaining budget",
    status: "Grant status",
    id: "Grant ID for Flow configuration",
    active: "Active policy",
    expired: "Expired",
    revoked: "Revoked",
    exhausted: "Budget exhausted",
  },
  ja: {
    title: "Shopify Flowのポイント権限",
    language: "言語",
    intro:
      "オーナー専用。上限付きの手動ポイント調整を許可します。購入やレビュー特典にはなりません。許可の状態はFlowの公開・有効化を示しません。",
    loading: "オーナー権限を確認中…",
    unavailable:
      "権限またはデータを確認できません。必要に応じてアプリを開き直して認証してください。",
    uncertain:
      "処理結果を確認できません。再送信やページの再読み込みをせず、元の処理を確認してください。",
    check: "元の処理を確認",
    unresolved: "結果は未確定です。処理を繰り返さないでください。",
    saved: "サーバーで確認しました。",
    invalid: "増減方向、正の整数の上限、将来の期限を指定し、承認してください。",
    credit: "ポイント追加を許可",
    debit: "ポイント減算を許可",
    maximum: "1処理あたりの絶対値上限",
    budget: "絶対値の合計上限",
    expires: "有効期限（現地時間）",
    consent:
      "社内ワークフローにこの上限を許可します。減算により残高がマイナスになる場合があります。",
    create: "権限を許可",
    reload: "更新",
    next: "次のページ",
    first: "最初のページ",
    revoke: "取り消す",
    confirm: "取り消しを確定",
    cancel: "キャンセル",
    empty: "このページに許可はありません。",
    remaining: "残り上限",
    status: "許可の状態",
    id: "Flow設定用の許可ID",
    active: "有効なポリシー",
    expired: "期限切れ",
    revoked: "取り消し済み",
    exhausted: "上限到達",
  },
  vi: {
    title: "Quyền điều chỉnh điểm qua Shopify Flow",
    language: "Ngôn ngữ",
    intro:
      "Chỉ chủ cửa hàng. Cấp quyền điều chỉnh điểm thủ công có giới hạn, không tạo giao dịch mua hay thưởng đánh giá. Trạng thái quyền không có nghĩa Flow đã triển khai hoặc bật.",
    loading: "Đang kiểm tra quyền chủ cửa hàng…",
    unavailable:
      "Không xác minh được quyền hoặc dữ liệu. Mở lại ứng dụng để xác thực nếu cần.",
    uncertain:
      "Chưa xác định được kết quả. Không gửi lại hoặc tải lại trang. Kiểm tra yêu cầu ban đầu bên dưới.",
    check: "Kiểm tra yêu cầu ban đầu",
    unresolved: "Chưa có kết quả xác nhận. Không lặp lại thao tác ghi.",
    saved: "Máy chủ đã xác nhận.",
    invalid:
      "Chọn chiều điều chỉnh, giới hạn nguyên dương, hạn trong tương lai và xác nhận cấp quyền.",
    credit: "Cho phép cộng điểm",
    debit: "Cho phép trừ điểm",
    maximum: "Giới hạn điểm tuyệt đối mỗi lần",
    budget: "Tổng ngân sách điểm tuyệt đối",
    expires: "Hết hạn (giờ địa phương)",
    consent:
      "Tôi cho phép các giới hạn này cho quy trình nội bộ. Trừ điểm có thể làm số dư âm.",
    create: "Cấp quyền",
    reload: "Làm mới",
    next: "Trang sau",
    first: "Trang đầu",
    revoke: "Thu hồi",
    confirm: "Xác nhận thu hồi",
    cancel: "Hủy",
    empty: "Không có quyền nào trên trang này.",
    remaining: "Ngân sách còn lại",
    status: "Trạng thái quyền",
    id: "Mã quyền dùng trong Flow",
    active: "Chính sách có hiệu lực",
    expired: "Hết hạn",
    revoked: "Đã thu hồi",
    exhausted: "Hết ngân sách",
  },
};
