export const importsAccessCopy = {
  en: {
    loading: "Loading import access…",
    error: "Import access could not be loaded.",
    reload: "Reload access",
  },
  ja: {
    loading: "インポート権限を読み込み中…",
    error: "インポート権限を読み込めませんでした。",
    reload: "権限を再読み込み",
  },
  vi: {
    loading: "Đang tải quyền nhập dữ liệu…",
    error: "Không tải được quyền nhập dữ liệu.",
    reload: "Tải lại quyền",
  },
};
export const importsCopy = {
  en: {
    title: "Historical loyalty import",
    notice:
      "Preview and stage opening balances, then refresh the import status to confirm a commit. Staging does not change points; verify processing with ledger reconciliation.",
    file: "Select file",
    format: "File format",
    inspect: "Preview file",
    stage: "Stage validated file",
    ready: "File ready",
    busy: "Processing…",
    error: "The request could not be confirmed. No automatic retry was made.",
    staged: "File staged. No points were committed.",
    denied: "Loyalty configuration permission is required.",
    rows: "Rows",
    total: "Opening points",
    row: "Row",
    before: "Before",
    after: "After",
    result: "Result",
    valid: "Valid",
    previous: "Previous",
    next: "Next",
    language: "Language",
    help: "CSV or JSON, up to 10 MiB and 50,000 rows. Required fields: shopifyCustomerId, openingBalance. Optional: birthdayMonth/birthdayDay (CSV), birthday (JSON), tierId.",
    customer_unavailable: "Customer unavailable",
    account_unavailable: "Account unavailable",
    tier_unavailable: "Tier unavailable",
    birthday_conflict: "Birthday conflicts with the existing registration",
    balance_overflow: "Balance exceeds storage limit",
  },
  ja: {
    title: "ロイヤルティ開始残高のインポート",
    notice:
      "開始残高をプレビューして準備保存し、状態を更新して反映を確認してください。準備保存ではポイントは変更されません。処理結果は台帳の照合で確認してください。",
    file: "ファイルを選択",
    format: "ファイル形式",
    inspect: "プレビュー",
    stage: "検証済みファイルを準備保存",
    ready: "ファイル準備完了",
    busy: "処理中…",
    error:
      "リクエストの結果を確認できませんでした。自動再試行は行っていません。",
    staged: "準備保存しました。ポイントは反映されていません。",
    denied: "ロイヤルティ設定権限が必要です。",
    rows: "行数",
    total: "開始ポイント",
    row: "行",
    before: "変更前",
    after: "変更後",
    result: "結果",
    valid: "有効",
    previous: "前へ",
    next: "次へ",
    language: "言語",
    help: "CSVまたはJSON、最大10 MiB・50,000行。必須: shopifyCustomerId、openingBalance。任意: birthdayMonth/birthdayDay（CSV）、birthday（JSON）、tierId。",
    customer_unavailable: "顧客を利用できません",
    account_unavailable: "アカウントを利用できません",
    tier_unavailable: "ランクを利用できません",
    birthday_conflict: "誕生日が既存の登録と一致しません",
    balance_overflow: "残高が保存上限を超えています",
  },
  vi: {
    title: "Nhập số dư loyalty ban đầu",
    notice:
      "Xem trước và lưu bản chuẩn bị, sau đó cập nhật trạng thái để xác nhận ghi điểm. Lưu bản chuẩn bị không thay đổi điểm; hãy đối soát sổ điểm để xác minh kết quả xử lý.",
    file: "Chọn tệp",
    format: "Định dạng tệp",
    inspect: "Xem trước",
    stage: "Lưu tệp đã kiểm tra",
    ready: "Tệp đã sẵn sàng",
    busy: "Đang xử lý…",
    error: "Không xác nhận được kết quả yêu cầu. Không tự động thử lại.",
    staged: "Đã lưu bản chuẩn bị. Chưa ghi điểm vào tài khoản.",
    denied: "Cần quyền cấu hình loyalty.",
    rows: "Số dòng",
    total: "Điểm ban đầu",
    row: "Dòng",
    before: "Trước",
    after: "Sau",
    result: "Kết quả",
    valid: "Hợp lệ",
    previous: "Trước",
    next: "Tiếp",
    language: "Ngôn ngữ",
    help: "CSV hoặc JSON, tối đa 10 MiB và 50.000 dòng. Bắt buộc: shopifyCustomerId, openingBalance. Tùy chọn: birthdayMonth/birthdayDay (CSV), birthday (JSON), tierId.",
    customer_unavailable: "Không thể sử dụng khách hàng",
    account_unavailable: "Không thể sử dụng tài khoản",
    tier_unavailable: "Không thể sử dụng hạng",
    birthday_conflict: "Ngày sinh không khớp với thông tin đã đăng ký",
    balance_overflow: "Số dư vượt giới hạn lưu trữ",
  },
};
