export const merchantReviewsCopy = {
  en: {
    title: "Reviews",
    language: "Language",
    home: "Overview",
    description:
      "Product reviews and purchase invitations. Store-experience reviews and Q&A are not available on this screen yet.",
    view: "View",
    reviews: "Product reviews",
    requests: "Invitations",
    status: "Status",
    all: "All",
    rating: "Rating",
    reload: "Load first page",
    next: "Next page",
    loading: "Loading…",
    empty: "No matching records.",
    denied: "You do not have permission to read this store’s reviews.",
    reauthenticate: "Reopen Weletic from Shopify Admin to authenticate again.",
    unavailable: "Reviews are unavailable. Reload the first page to try again.",
    verified: "Verified purchase",
    unverified: "Purchase not verified",
    incentive: "Incentivized",
    photos: "Photos",
    reply: "Merchant reply",
    scheduled: "Scheduled",
    expires: "Expires",
    attempts: "Delivery attempts",
    deliveryError: "Delivery needs attention",
    page: "Page",
    statuses: {
      pending: "Pending",
      published: "Published",
      hidden: "Hidden",
      rejected: "Rejected",
      redacted: "Redacted",
      queued: "Queued",
      sending: "Sending",
      sent: "Sent",
      submitted: "Submitted",
      expired: "Expired",
      cancelled: "Cancelled",
      failed: "Failed",
    },
  },
  ja: {
    title: "レビュー",
    language: "言語",
    home: "概要",
    description:
      "商品レビューと購入者への依頼。ストア評価とQ&Aは、この画面ではまだ利用できません。",
    view: "表示",
    reviews: "商品レビュー",
    requests: "レビュー依頼",
    status: "状態",
    all: "すべて",
    rating: "評価",
    reload: "最初のページを読み込む",
    next: "次のページ",
    loading: "読み込み中…",
    empty: "該当するデータはありません。",
    denied: "このストアのレビューを閲覧する権限がありません。",
    reauthenticate: "Shopify管理画面からWeleticを開き直して認証してください。",
    unavailable:
      "レビューを取得できません。最初のページを再読み込みしてください。",
    verified: "購入確認済み",
    unverified: "購入未確認",
    incentive: "特典あり",
    photos: "写真",
    reply: "ストアからの返信",
    scheduled: "送信予定",
    expires: "有効期限",
    attempts: "送信試行回数",
    deliveryError: "配信状況の確認が必要です",
    page: "ページ",
    statuses: {
      pending: "確認待ち",
      published: "公開済み",
      hidden: "非表示",
      rejected: "却下",
      redacted: "削除処理済み",
      queued: "待機中",
      sending: "送信中",
      sent: "送信済み",
      submitted: "投稿済み",
      expired: "期限切れ",
      cancelled: "キャンセル済み",
      failed: "失敗",
    },
  },
  vi: {
    title: "Đánh giá",
    language: "Ngôn ngữ",
    home: "Tổng quan",
    description:
      "Đánh giá sản phẩm và lời mời sau mua hàng. Đánh giá cửa hàng và hỏi đáp chưa có trên màn hình này.",
    view: "Chế độ xem",
    reviews: "Đánh giá sản phẩm",
    requests: "Lời mời",
    status: "Trạng thái",
    all: "Tất cả",
    rating: "Số sao",
    reload: "Tải trang đầu",
    next: "Trang tiếp",
    loading: "Đang tải…",
    empty: "Không có dữ liệu phù hợp.",
    denied: "Bạn không có quyền đọc đánh giá của cửa hàng này.",
    reauthenticate: "Mở lại Weletic từ Shopify Admin để xác thực.",
    unavailable: "Không thể tải đánh giá. Hãy tải lại trang đầu để thử lại.",
    verified: "Đã xác minh mua hàng",
    unverified: "Chưa xác minh mua hàng",
    incentive: "Có ưu đãi",
    photos: "Ảnh",
    reply: "Phản hồi của cửa hàng",
    scheduled: "Lịch gửi",
    expires: "Hết hạn",
    attempts: "Số lần gửi",
    deliveryError: "Cần kiểm tra việc gửi",
    page: "Trang",
    statuses: {
      pending: "Chờ duyệt",
      published: "Đã công khai",
      hidden: "Đã ẩn",
      rejected: "Đã từ chối",
      redacted: "Đã xóa dữ liệu",
      queued: "Đang chờ",
      sending: "Đang gửi",
      sent: "Đã gửi",
      submitted: "Đã đánh giá",
      expired: "Hết hạn",
      cancelled: "Đã hủy",
      failed: "Thất bại",
    },
  },
} as const;
