export const reviewIncentiveEditorCopy = {
  en: {
    load: "Load incentive settings",
    loading: "Loading incentive settings…",
    loadFailed:
      "Could not load settings. Check your access or reopen the app, then retry.",
    search: "Search coupon names",
    find: "Search",
    more: "More coupons",
    active: "Active saved promise",
    legacy:
      "Legacy incentive behavior remains in effect. A draft does not replace it.",
    empty:
      "No matching coupon candidates. Your selected coupon is preserved. Saving rechecks all eligibility and catalog terms.",
    heading: "Review incentive draft",
    help: "Saving a draft does not activate incentives or change existing invitations. Rewards are for valid participation, regardless of rating or publication.",
    kind: "Incentive",
    none: "No incentive",
    points: "Points",
    coupon: "Coupon",
    base: "Base points",
    photo: "Photo bonus",
    video: "Saved video bonus (currently unavailable)",
    cap: "Maximum points per order",
    couponLabel: "Reward catalog coupon",
    choose: "Choose a coupon",
    invalid: "Check the fields and select an available coupon.",
    save: "Save draft",
    saved:
      "Draft saved. Reload to review the saved promise; incentives remain unchanged.",
    reload: "Reload policy",
    stale: "Policy state may have changed. Reload before saving again.",
    busy: "Saving draft…",
    failed:
      "The save was not confirmed. Do not resubmit; reload the policy first.",
    denied: "You do not have permission to configure reviews.",
    auth: "Reopen the app to refresh your Shopify session.",
    preview: "Previously saved promise",
    unavailable:
      "The saved disclosure is unavailable. This is not an activation-ready policy.",
    discard: "Discard unsaved changes and reload?",
  },
  ja: {
    load: "特典設定を読み込む",
    loading: "特典設定を読み込み中…",
    loadFailed:
      "設定を読み込めませんでした。権限を確認するかアプリを開き直して再試行してください。",
    search: "クーポン名を検索",
    find: "検索",
    more: "クーポンをさらに表示",
    active: "有効な保存済み条件",
    legacy: "従来の特典動作が適用されています。下書きでは置き換わりません。",
    empty:
      "該当するクーポン候補はありません。選択済みのクーポンは保持されます。保存時に対象条件を再確認します。",
    heading: "レビュー特典の下書き",
    help: "下書きを保存しても特典は有効にならず、既存の案内は変更されません。特典は評価や公開状況に関係なく、有効な投稿が対象です。",
    kind: "特典",
    none: "特典なし",
    points: "ポイント",
    coupon: "クーポン",
    base: "基本ポイント",
    photo: "写真ボーナス",
    video: "保存済み動画ボーナス（現在未対応）",
    cap: "1注文あたりのポイント上限",
    couponLabel: "特典カタログのクーポン",
    choose: "クーポンを選択",
    invalid: "入力内容を確認し、利用可能なクーポンを選択してください。",
    save: "下書きを保存",
    saved:
      "下書きを保存しました。再読み込みして条件を確認してください。特典の有効状態は変わりません。",
    reload: "設定を再読み込み",
    stale:
      "設定が変更された可能性があります。再読み込みしてから保存してください。",
    busy: "下書きを保存中…",
    failed:
      "保存を確認できませんでした。再送信せず、設定を再読み込みしてください。",
    denied: "レビューを設定する権限がありません。",
    auth: "アプリを開き直してShopifyセッションを更新してください。",
    preview: "以前に保存した特典条件",
    unavailable:
      "保存された条件を表示できません。この設定は有効化できる状態ではありません。",
    discard: "未保存の変更を破棄して再読み込みしますか？",
  },
  vi: {
    load: "Tải cài đặt ưu đãi",
    loading: "Đang tải cài đặt ưu đãi…",
    loadFailed:
      "Không thể tải cài đặt. Kiểm tra quyền hoặc mở lại ứng dụng rồi thử lại.",
    search: "Tìm tên phiếu giảm giá",
    find: "Tìm kiếm",
    more: "Thêm phiếu giảm giá",
    active: "Cam kết đang áp dụng",
    legacy:
      "Cơ chế ưu đãi cũ vẫn đang áp dụng. Bản nháp không thay thế cơ chế này.",
    empty:
      "Không có phiếu giảm giá phù hợp. Lựa chọn hiện tại được giữ nguyên. Khi lưu, hệ thống kiểm tra lại điều kiện và danh mục.",
    heading: "Bản nháp ưu đãi đánh giá",
    help: "Lưu bản nháp không kích hoạt ưu đãi hoặc thay đổi lời mời hiện có. Phần thưởng dành cho đánh giá hợp lệ, không phụ thuộc xếp hạng hay việc công khai.",
    kind: "Ưu đãi",
    none: "Không thưởng",
    points: "Điểm",
    coupon: "Phiếu giảm giá",
    base: "Điểm cơ bản",
    photo: "Thưởng ảnh",
    video: "Thưởng video đã lưu (hiện chưa hỗ trợ)",
    cap: "Điểm tối đa mỗi đơn hàng",
    couponLabel: "Phiếu giảm giá trong danh mục",
    choose: "Chọn phiếu giảm giá",
    invalid: "Kiểm tra các trường và chọn phiếu giảm giá khả dụng.",
    save: "Lưu bản nháp",
    saved:
      "Đã lưu bản nháp. Tải lại để kiểm tra cam kết đã lưu; ưu đãi chưa thay đổi.",
    reload: "Tải lại chính sách",
    stale: "Chính sách có thể đã thay đổi. Tải lại trước khi lưu tiếp.",
    busy: "Đang lưu bản nháp…",
    failed:
      "Chưa xác nhận được việc lưu. Không gửi lại; hãy tải lại chính sách trước.",
    denied: "Bạn không có quyền cấu hình đánh giá.",
    auth: "Mở lại ứng dụng để làm mới phiên Shopify.",
    preview: "Cam kết đã lưu trước đó",
    unavailable:
      "Không thể hiển thị cam kết đã lưu. Chính sách này chưa sẵn sàng kích hoạt.",
    discard: "Bỏ thay đổi chưa lưu và tải lại?",
  },
} as const;
