export const reviewDeliveryCopy = {
  en: {
    title: "Email delivery history",
    initial: "Initial invitation",
    reminder: "Reminder",
    scheduled: "Scheduled",
    confirmed: "Provider confirmed",
    attempts: "Attempts",
    missing: "Delivery history is unavailable from this reader.",
    empty: "No reminder deliveries recorded.",
    note: "Provider confirmation does not prove inbox delivery or that the email was read. An unconfirmed attempt may have sent; do not resend it manually without reconciliation.",
    outcomes: {
      queued: "Queued",
      sending: "Attempt in progress",
      confirmed: "Provider confirmed",
      unconfirmed: "Outcome unconfirmed — needs reconciliation",
      cancelled: "Cancelled before any recorded attempt",
      unavailable: "Evidence unavailable",
    },
  },
  ja: {
    title: "メール送信履歴",
    initial: "最初の招待",
    reminder: "リマインダー",
    scheduled: "送信予定",
    confirmed: "プロバイダー確認日時",
    attempts: "試行回数",
    missing: "この読み取り元から送信履歴を取得できません。",
    empty: "記録されたリマインダーはありません。",
    note: "プロバイダーの確認は受信トレイへの到達や開封を証明しません。結果未確認の試行は送信済みの可能性があるため、照合せずに手動再送しないでください。",
    outcomes: {
      queued: "待機中",
      sending: "送信試行中",
      confirmed: "プロバイダー確認済み",
      unconfirmed: "結果未確認・照合が必要",
      cancelled: "記録された試行前にキャンセル",
      unavailable: "確認情報なし",
    },
  },
  vi: {
    title: "Lịch sử gửi email",
    initial: "Lời mời đầu tiên",
    reminder: "Lần nhắc",
    scheduled: "Lịch gửi",
    confirmed: "Nhà cung cấp đã xác nhận",
    attempts: "Số lần thử",
    missing: "Nguồn đọc này chưa cung cấp lịch sử gửi.",
    empty: "Chưa có bản ghi gửi nhắc.",
    note: "Xác nhận của nhà cung cấp không chứng minh email đã vào hộp thư hoặc được đọc. Lần gửi chưa rõ kết quả có thể đã được gửi; không gửi lại thủ công khi chưa đối soát.",
    outcomes: {
      queued: "Đang chờ",
      sending: "Đang thử gửi",
      confirmed: "Nhà cung cấp đã xác nhận",
      unconfirmed: "Chưa rõ kết quả — cần đối soát",
      cancelled: "Đã hủy trước lần thử được ghi nhận",
      unavailable: "Chưa có bằng chứng",
    },
  },
} as const;
