export const shopperCopy = {
  en: {
    title: "Customers",
    subtitle: "One shopper profile for loyalty, referrals and reviews.",
    search: "Search customers",
    searchHint: "Name, email or Shopify customer ID",
    open: "Open profile",
    empty: "No visible customers on this page.",
    noAccount: "Not enrolled in loyalty",
    enrolled: "Loyalty member",
    loading: "Loading…",
    error: "Customer data is unavailable. Check your access or try again.",
    retry: "Try again",
    next: "Next page",
    first: "First page",
    back: "All customers",
    language: "Language",
    overview: "Overview",
    purchases: "Purchases",
    points: "Points",
    referrals: "Referrals",
    reviews: "Reviews",
    rewards: "Rewards",
    review_requests: "Review requests",
    emptyHistory: "No records on this page.",
    balance: "Points balance",
    pending: "Pending points",
    tier: "VIP tier",
    email: "Email",
    phone: "Phone",
    customerId: "Shopify customer ID",
    consent: "Communication preferences",
    consentUnknown:
      "The Shopify marketing flag is not consent evidence. Consent history and suppression status are not yet available here.",
    marketing: "Shopify marketing flag",
    yes: "Yes",
    no: "No",
    coverage: "Available history",
    coverageNote:
      "Locally recorded orders, native product reviews and existing reward redemptions. Review-request and referral email timestamps do not prove inbox delivery. Other communication journeys are not yet included.",
    date: "Recorded (UTC)",
    orderDate: "Order placed (UTC)",
    record: "Record",
    status: "Status",
    net: "Accounting net",
    total: "Accounting total",
    delta: "Points change",
    pendingDelta: "Pending change",
    after: "Balance after",
    role: "Referral role",
    awarded: "Points awarded",
    emailed: "Friend email recorded (UTC)",
    rating: "Rating",
    titleLabel: "Title",
    rewardStatus: "Incentive status",
    cost: "Points spent",
    kind: "Reward type",
    entryType: "Ledger entry type",
    paused: "Paused by safety switch",
    used: "Used (UTC)",
    expires: "Expires (UTC)",
    scheduled: "Scheduled (UTC)",
    sent: "Send recorded (UTC)",
    attempts: "Attempts",
    modules: "Module settings",
    loyalty: "Loyalty",
    enabled: "Enabled",
    disabled: "Disabled",
    historical: "Turning a module off does not erase its history.",
    originalTotals:
      "Order amounts are stored accounting values, not post-refund revenue or a cross-currency total.",
  },
  ja: {
    title: "顧客",
    subtitle: "ロイヤルティ・紹介・レビューを一つの顧客プロフィールで確認。",
    search: "顧客を検索",
    searchHint: "氏名、メール、Shopify顧客ID",
    open: "プロフィールを開く",
    empty: "このページに表示可能な顧客はいません。",
    noAccount: "ロイヤルティ未登録",
    enrolled: "ロイヤルティ会員",
    loading: "読み込み中…",
    error:
      "顧客データを取得できません。アクセス権を確認するか、再試行してください。",
    retry: "再試行",
    next: "次のページ",
    first: "最初のページ",
    back: "顧客一覧",
    language: "言語",
    overview: "概要",
    purchases: "購入履歴",
    points: "ポイント",
    referrals: "紹介",
    reviews: "レビュー",
    rewards: "特典",
    review_requests: "レビュー依頼",
    emptyHistory: "このページに記録はありません。",
    balance: "ポイント残高",
    pending: "保留ポイント",
    tier: "VIPランク",
    email: "メール",
    phone: "電話番号",
    customerId: "Shopify顧客ID",
    consent: "配信設定",
    consentUnknown:
      "Shopifyのマーケティングフラグは同意の証拠ではありません。同意履歴と配信停止状態はここでは未対応です。",
    marketing: "Shopifyマーケティングフラグ",
    yes: "はい",
    no: "いいえ",
    coverage: "表示される履歴",
    coverageNote:
      "保存済みの注文、ネイティブ商品レビュー、既存の特典交換が対象です。依頼・紹介メールの送信記録は受信箱への配信を証明しません。他の配信履歴は未対応です。",
    date: "記録日時（UTC）",
    orderDate: "注文日時（UTC）",
    record: "記録",
    status: "状態",
    net: "会計純額",
    total: "会計合計",
    delta: "ポイント増減",
    pendingDelta: "保留増減",
    after: "処理後残高",
    role: "紹介での役割",
    awarded: "付与ポイント",
    emailed: "友人メール記録（UTC）",
    rating: "評価",
    titleLabel: "タイトル",
    rewardStatus: "インセンティブ状態",
    cost: "使用ポイント",
    kind: "特典種別",
    entryType: "台帳記録種別",
    paused: "安全スイッチにより停止中",
    used: "利用日時（UTC）",
    expires: "有効期限（UTC）",
    scheduled: "予定日時（UTC）",
    sent: "送信記録（UTC）",
    attempts: "試行回数",
    modules: "機能設定",
    loyalty: "ロイヤルティ",
    enabled: "有効",
    disabled: "無効",
    historical: "機能を無効にしても履歴は削除されません。",
    originalTotals:
      "金額は保存済みの会計値です。返金後の売上や通貨を合算した総額ではありません。",
  },
  vi: {
    title: "Khách hàng",
    subtitle: "Một hồ sơ khách hàng chung cho loyalty, giới thiệu và đánh giá.",
    search: "Tìm khách hàng",
    searchHint: "Tên, email hoặc ID khách hàng Shopify",
    open: "Mở hồ sơ",
    empty: "Không có khách hàng hiển thị trên trang này.",
    noAccount: "Chưa tham gia loyalty",
    enrolled: "Thành viên loyalty",
    loading: "Đang tải…",
    error:
      "Không thể tải dữ liệu khách hàng. Kiểm tra quyền truy cập hoặc thử lại.",
    retry: "Thử lại",
    next: "Trang tiếp",
    first: "Trang đầu",
    back: "Tất cả khách hàng",
    language: "Ngôn ngữ",
    overview: "Tổng quan",
    purchases: "Mua hàng",
    points: "Điểm",
    referrals: "Giới thiệu",
    reviews: "Đánh giá",
    rewards: "Phần thưởng",
    review_requests: "Yêu cầu đánh giá",
    emptyHistory: "Trang này chưa có bản ghi.",
    balance: "Số dư điểm",
    pending: "Điểm chờ",
    tier: "Hạng VIP",
    email: "Email",
    phone: "Điện thoại",
    customerId: "ID khách hàng Shopify",
    consent: "Tùy chọn liên lạc",
    consentUnknown:
      "Cờ tiếp thị Shopify không phải bằng chứng đồng ý. Lịch sử đồng ý và trạng thái chặn gửi chưa có tại đây.",
    marketing: "Cờ tiếp thị Shopify",
    yes: "Có",
    no: "Không",
    coverage: "Lịch sử hiện có",
    coverageNote:
      "Bao gồm đơn hàng đã ghi nhận, đánh giá sản phẩm nội bộ và các lần đổi thưởng hiện có. Thời điểm gửi email đánh giá hoặc giới thiệu không chứng minh email đã đến hộp thư. Các luồng liên lạc khác chưa được tích hợp.",
    date: "Ngày ghi nhận (UTC)",
    orderDate: "Ngày đặt hàng (UTC)",
    record: "Bản ghi",
    status: "Trạng thái",
    net: "Giá trị thuần kế toán",
    total: "Tổng kế toán",
    delta: "Thay đổi điểm",
    pendingDelta: "Thay đổi điểm chờ",
    after: "Số dư sau",
    role: "Vai trò giới thiệu",
    awarded: "Điểm được tặng",
    emailed: "Ghi nhận email cho bạn bè (UTC)",
    rating: "Số sao",
    titleLabel: "Tiêu đề",
    rewardStatus: "Trạng thái ưu đãi",
    cost: "Điểm đã dùng",
    kind: "Loại phần thưởng",
    entryType: "Loại bút toán điểm",
    paused: "Tạm dừng bởi công tắc an toàn",
    used: "Ngày sử dụng (UTC)",
    expires: "Hết hạn (UTC)",
    scheduled: "Lịch gửi (UTC)",
    sent: "Ghi nhận gửi (UTC)",
    attempts: "Số lần thử",
    modules: "Cài đặt tính năng",
    loyalty: "Loyalty",
    enabled: "Bật",
    disabled: "Tắt",
    historical: "Tắt tính năng không xóa lịch sử.",
    originalTotals:
      "Số tiền là dữ liệu kế toán đã lưu, không phải doanh thu sau hoàn tiền hoặc tổng cộng nhiều loại tiền tệ.",
  },
} satisfies Record<string, Record<string, string>>;
export type ShopperLocale = keyof typeof shopperCopy;
export type ShopperCopy = { [K in keyof typeof shopperCopy.en]: string };
